INSERT INTO currency () VALUES ('Abkhazia', 'Abkhazian apsar', NULL, NULL, NULL, (none));
INSERT INTO currency () VALUES ('Abkhazia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO currency () VALUES ('Afghanistan', 'Afghan afghani', 'Af or Afs (pl.)', 'AFN', 'Pul', 100);
INSERT INTO currency () VALUES ('Akrotiri and Dhekelia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Albania', 'Albanian lek', 'Lek', 'ALL', 'Qintar', 100);
INSERT INTO currency () VALUES ('Alderney', 'Alderney pound', '£', NULL, 'Penny', 100);
INSERT INTO currency () VALUES ('Alderney', 'Sterling banknotes are issued by the Bank of England and by some banks in Scotland and Northern Ireland (incl. Danske Bank). Laws on legal tender vary between various jurisdictions.', '£', 'GBP', 'Penny', 100);
INSERT INTO currency () VALUES ('Alderney', 'Guernsey pound', '£', NULL, 'Penny', 100);
INSERT INTO currency () VALUES ('Algeria', 'Algerian dinar', 'DA', 'DZD', 'Santeem', 100);
INSERT INTO currency () VALUES ('Andorra', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Angola', 'Angolan kwanza', 'Kz', 'AOA', 'Cêntimo', 100);
INSERT INTO currency () VALUES ('Anguilla', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Antigua and Barbuda', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Argentina', 'Argentine peso', '$', 'ARS', 'Centavo', 100);
INSERT INTO currency () VALUES ('Armenia', 'Armenian dram', '֏', 'AMD', 'Luma', 100);
INSERT INTO currency () VALUES ('Artsakh', 'Artsakh dram', 'դր.', NULL, 'Luma', 100);
INSERT INTO currency () VALUES ('Artsakh', 'Armenian dram', '֏', 'AMD', 'Luma', 100);
INSERT INTO currency () VALUES ('Aruba', 'Aruban florin', 'ƒ', 'AWG', 'Cent', 100);
INSERT INTO currency () VALUES ('Ascension Island', 'Saint Helena pound', '£', 'SHP', 'Penny', 100);
INSERT INTO currency () VALUES ('Australia', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO currency () VALUES ('Austria', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Azerbaijan', 'Azerbaijani manat', '₼', 'AZN', 'Qəpik', 100);
INSERT INTO currency () VALUES ('Bahamas, The', 'Bahamian dollar', '$', 'BSD', 'Cent', 100);
INSERT INTO currency () VALUES ('Bahrain', 'Bahraini dinar', 'BD', 'BHD', 'Fils', 1000);
INSERT INTO currency () VALUES ('Bangladesh', 'Bangladeshi taka', '৳', 'BDT', 'Poisha', 100);
INSERT INTO currency () VALUES ('Barbados', 'Barbadian dollar', '$', 'BBD', 'Cent', 100);
INSERT INTO currency () VALUES ('Belarus', 'Belarusian rubel', 'Rbl or Rbls (pl.)', 'BYN', 'Copeck', 100);
INSERT INTO currency () VALUES ('Belgium', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Belize', 'Belize dollar', '$', 'BZD', 'Cent', 100);
INSERT INTO currency () VALUES ('Benin', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Bermuda', 'Bermudian dollar', '$', 'BMD', 'Cent', 100);
INSERT INTO currency () VALUES ('Bhutan', 'Bhutanese ngultrum', 'Nu', 'BTN', 'Chetrum', 100);
INSERT INTO currency () VALUES ('Bhutan', 'Indian rupee', '₹', 'INR', 'Paisa', 100);
INSERT INTO currency () VALUES ('Bolivia', 'Bolivian boliviano', 'Bs', 'BOB', 'Centavo', 100);
INSERT INTO currency () VALUES ('Bonaire', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'KM', 'BAM', 'Fening', 100);
INSERT INTO currency () VALUES ('Botswana', 'Botswana pula', 'P', 'BWP', 'Thebe', 100);
INSERT INTO currency () VALUES ('Brazil', 'Brazilian real', 'R$', 'BRL', 'Centavo', 100);
INSERT INTO currency () VALUES ('British Indian Ocean Territory', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('British Virgin Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Brunei', 'Brunei dollar', '$', 'BND', 'Sen', 100);
INSERT INTO currency () VALUES ('Brunei', 'Singapore dollar', '$', 'SGD', 'Cent', 100);
INSERT INTO currency () VALUES ('Bulgaria', 'Bulgarian lev', 'Lev', 'BGN', 'Stotinka', 100);
INSERT INTO currency () VALUES ('Burkina Faso', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Burundi', 'Burundian franc', 'Fr', 'BIF', 'Centime', 100);
INSERT INTO currency () VALUES ('Cambodia', 'Cambodian riel', 'CR', 'KHR', 'Sen', 100);
INSERT INTO currency () VALUES ('Cameroon', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Canada', 'Canadian dollar', '$', 'CAD', 'Cent', 100);
INSERT INTO currency () VALUES ('Cape Verde', 'Cape Verdean escudo', '$', 'CVE', 'Centavo', 100);
INSERT INTO currency () VALUES ('Cayman Islands', 'Cayman Islands dollar', '$', 'KYD', 'Cent', 100);
INSERT INTO currency () VALUES ('Central African Republic', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Central African Republic', 'Bitcoin (as legal tender)', '₿', NULL, 'Satoshi', 100000000);
INSERT INTO currency () VALUES ('Chad', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Chile', 'Chilean peso', '$', 'CLP', 'Centavo', 100);
INSERT INTO currency () VALUES ('China, People''s Republic of', 'Renminbi', '¥', 'CNY', 'Jiao', 10);
INSERT INTO currency () VALUES ('Colombia', 'Colombian peso', '$', 'COP', 'Centavo', 100);
INSERT INTO currency () VALUES ('Comoros', 'Comorian franc', 'Fr', 'KMF', 'Centime', 100);
INSERT INTO currency () VALUES ('Congo, Democratic Republic of the', 'Congolese franc', 'Fr', 'CDF', 'Centime', 100);
INSERT INTO currency () VALUES ('Congo, Republic of the', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Cook Islands', 'Cook Islands dollar', '$', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('Cook Islands', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO currency () VALUES ('Costa Rica', 'Costa Rican colón', '₡', 'CRC', 'Céntimo', 100);
INSERT INTO currency () VALUES ('Côte d''Ivoire', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Croatia', 'Croatian kuna', 'kn', 'HRK', 'Lipa', 100);
INSERT INTO currency () VALUES ('Cuba', 'Cuban peso', '$', 'CUP', 'Centavo', 100);
INSERT INTO currency () VALUES ('Curaçao', 'Netherlands Antillean guilder', 'ƒ', 'ANG', 'Cent', 100);
INSERT INTO currency () VALUES ('Cyprus', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Czech Republic', 'Czech koruna', 'Kč', 'CZK', 'Heller', 100);
INSERT INTO currency () VALUES ('Denmark', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO currency () VALUES ('Djibouti', 'Djiboutian franc', 'Fr', 'DJF', 'Centime', 100);
INSERT INTO currency () VALUES ('Dominica', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Dominican Republic', 'Dominican peso', '$', 'DOP', 'Centavo', 100);
INSERT INTO currency () VALUES ('East Timor', 'United States dollar', '$', 'USD', 'Centavo', 100);
INSERT INTO currency () VALUES ('Ecuador', 'United States dollar', '$', 'USD', 'Centavo', 100);
INSERT INTO currency () VALUES ('Egypt', 'Egyptian pound', 'LE', 'EGP', 'Piastre', 100);
INSERT INTO currency () VALUES ('El Salvador', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('El Salvador', 'Bitcoin (as legal tender)', '₿', NULL, 'Satoshi', 100000000);
INSERT INTO currency () VALUES ('Equatorial Guinea', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Eritrea', 'Eritrean nakfa', 'Nkf', 'ERN', 'Cent', 100);
INSERT INTO currency () VALUES ('Estonia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Eswatini', 'Swazi lilangeni', 'L or E (pl.)', 'SZL', 'Cent', 100);
INSERT INTO currency () VALUES ('Eswatini', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO currency () VALUES ('Ethiopia', 'Ethiopian birr', 'Br', 'ETB', 'Santim', 100);
INSERT INTO currency () VALUES ('Falkland Islands', 'Falkland Islands pound', '£', 'FKP', 'Penny', 100);
INSERT INTO currency () VALUES ('Faroe Islands', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO currency () VALUES ('Faroe Islands', 'Faroese króna', 'kr', NULL, 'Oyra', 100);
INSERT INTO currency () VALUES ('Fiji', 'Fijian dollar', '$', 'FJD', 'Cent', 100);
INSERT INTO currency () VALUES ('Finland', 'Euro', '€', 'EUR', 'Sentti', 100);
INSERT INTO currency () VALUES ('France', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('French Polynesia', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO currency () VALUES ('Gabon', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO currency () VALUES ('Gambia, The', 'Gambian dalasi', 'D', 'GMD', 'Butut', 100);
INSERT INTO currency () VALUES ('Georgia', 'Georgian lari', '₾', 'GEL', 'Tetri', 100);
INSERT INTO currency () VALUES ('Germany', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Ghana', 'Ghanaian cedi', '₵', 'GHS', 'Pesewa', 100);
INSERT INTO currency () VALUES ('Gibraltar', 'Gibraltar pound', '£', 'GIP', 'Penny', 100);
INSERT INTO currency () VALUES ('Greece', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Greenland', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO currency () VALUES ('Grenada', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Guatemala', 'Guatemalan quetzal', 'Q', 'GTQ', 'Centavo', 100);
INSERT INTO currency () VALUES ('Guernsey', 'Guernsey pound', '£', NULL, 'Penny', 100);
INSERT INTO currency () VALUES ('Guernsey', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO currency () VALUES ('Guinea', 'Guinean franc', 'Fr', 'GNF', 'Centime', 100);
INSERT INTO currency () VALUES ('Guinea-Bissau', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Guyana', 'Guyanese dollar', '$', 'GYD', 'Cent', 100);
INSERT INTO currency () VALUES ('Haiti', 'Haitian gourde', 'G', 'HTG', 'Centime', 100);
INSERT INTO currency () VALUES ('Honduras', 'Honduran lempira', 'L', 'HNL', 'Centavo', 100);
INSERT INTO currency () VALUES ('Hong Kong', 'Hong Kong dollar', '$', 'HKD', 'Cent', 100);
INSERT INTO currency () VALUES ('Hungary', 'Hungarian forint', 'Ft', 'HUF', 'Fillér', 100);
INSERT INTO currency () VALUES ('Iceland', 'Icelandic króna', 'kr', 'ISK', 'Eyrir', 100);
INSERT INTO currency () VALUES ('India', 'Indian rupee', '₹', 'INR', 'Paisa', 100);
INSERT INTO currency () VALUES ('Indonesia', 'Indonesian rupiah', 'Rp', 'IDR', 'Sen', 100);
INSERT INTO currency () VALUES ('Iran', 'Iranian rial', 'Rl or Rls (pl.)', 'IRR', 'Rial', 1);
INSERT INTO currency () VALUES ('Iraq', 'Iraqi dinar', 'ID', 'IQD', 'Fils', 1000);
INSERT INTO currency () VALUES ('Ireland', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Isle of Man', 'Manx pound', '£', NULL, 'Penny', 100);
INSERT INTO currency () VALUES ('Isle of Man', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO currency () VALUES ('Israel', 'Israeli new shekel', '₪', 'ILS', 'Agora', 100);
INSERT INTO currency () VALUES ('Italy', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Jamaica', 'Jamaican dollar', '$', 'JMD', 'Cent', 100);
INSERT INTO currency () VALUES ('Japan', 'Japanese yen', '¥', 'JPY', 'Sen', 100);
INSERT INTO currency () VALUES ('Jersey', 'Jersey pound', '£', NULL, 'Penny', 100);
INSERT INTO currency () VALUES ('Jersey', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO currency () VALUES ('Jordan', 'Jordanian dinar', 'JD', 'JOD', 'Piastre', 100);
INSERT INTO currency () VALUES ('Kazakhstan', 'Kazakhstani tenge', '₸', 'KZT', 'Tıyn', 100);
INSERT INTO currency () VALUES ('Kenya', 'Kenyan shilling', 'Sh or Shs (pl.)', 'KES', 'Cent', 100);
INSERT INTO currency () VALUES ('Kiribati', 'Kiribati dollar', '$', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('Kiribati', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO currency () VALUES ('Korea, North', 'North Korean won', '₩', 'KPW', 'Chon', 100);
INSERT INTO currency () VALUES ('Korea, South', 'South Korean won', '₩', 'KRW', 'Jeon', 100);
INSERT INTO currency () VALUES ('Kosovo', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Kuwait', 'Kuwaiti dinar', 'KD', 'KWD', 'Fils', 1000);
INSERT INTO currency () VALUES ('Kyrgyzstan', 'Kyrgyz som', 'som', 'KGS', 'Tyiyn', 100);
INSERT INTO currency () VALUES ('Laos', 'Lao kip', '₭', 'LAK', 'Att', 100);
INSERT INTO currency () VALUES ('Latvia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Lebanon', 'Lebanese pound', 'LL', 'LBP', 'Piastre', 100);
INSERT INTO currency () VALUES ('Lesotho', 'Lesotho loti', 'L or M (pl.)', 'LSL', 'Sente', 100);
INSERT INTO currency () VALUES ('Lesotho', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO currency () VALUES ('Liberia', 'Liberian dollar', '$', 'LRD', 'Cent', 100);
INSERT INTO currency () VALUES ('Libya', 'Libyan dinar', 'LD', 'LYD', 'Dirham', 1000);
INSERT INTO currency () VALUES ('Liechtenstein', 'Swiss franc', 'Fr', 'CHF', 'Rappen', 100);
INSERT INTO currency () VALUES ('Lithuania', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Luxembourg', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Macau', 'Macanese pataca', 'MOP$', 'MOP', 'Avo', 100);
INSERT INTO currency () VALUES ('Macau', 'Hong Kong dollar', '$', 'HKD', 'Cent', 100);
INSERT INTO currency () VALUES ('Madagascar', 'Malagasy ariary', 'Ar', 'MGA', 'Iraimbilanja', 5);
INSERT INTO currency () VALUES ('Malawi', 'Malawian kwacha', 'K', 'MWK', 'Tambala', 100);
INSERT INTO currency () VALUES ('Malaysia', 'Malaysian ringgit', 'RM', 'MYR', 'Sen', 100);
INSERT INTO currency () VALUES ('Maldives', 'Maldivian rufiyaa', 'Rf', 'MVR', 'Laari', 100);
INSERT INTO currency () VALUES ('Mali', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Malta', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Marshall Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Mauritania', 'Mauritanian ouguiya', 'UM', 'MRU', 'Khoums', 5);
INSERT INTO currency () VALUES ('Mauritius', 'Mauritian rupee', 'Re or Rs (pl.)', 'MUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Mexico', 'Mexican peso', '$', 'MXN', 'Centavo', 100);
INSERT INTO currency () VALUES ('Micronesia', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Moldova', 'Moldovan leu', 'Leu or Lei (pl.)', 'MDL', 'Ban', 100);
INSERT INTO currency () VALUES ('Monaco', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Mongolia', 'Mongolian tögrög', '₮', 'MNT', 'Möngö', 100);
INSERT INTO currency () VALUES ('Montenegro', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Montserrat', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Morocco', 'Moroccan dirham', 'DH', 'MAD', 'Centime', 100);
INSERT INTO currency () VALUES ('Mozambique', 'Mozambican metical', 'Mt', 'MZN', 'Centavo', 100);
INSERT INTO currency () VALUES ('Myanmar', 'Burmese kyat', 'K or Ks (pl.)', 'MMK', 'Pya', 100);
INSERT INTO currency () VALUES ('Namibia', 'Namibian dollar', '$', 'NAD', 'Cent', 100);
INSERT INTO currency () VALUES ('Namibia', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO currency () VALUES ('Nauru', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO currency () VALUES ('Nepal', 'Nepalese rupee', 'Re or Rs (pl.)', 'NPR', 'Paisa', 100);
INSERT INTO currency () VALUES ('Netherlands', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('New Caledonia', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO currency () VALUES ('New Zealand', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO currency () VALUES ('Nicaragua', 'Nicaraguan córdoba', 'C$', 'NIO', 'Centavo', 100);
INSERT INTO currency () VALUES ('Niger', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Nigeria', 'Nigerian naira', '₦', 'NGN', 'Kobo', 100);
INSERT INTO currency () VALUES ('Niue', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO currency () VALUES ('Niue', 'Niue dollar', '$', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('North Macedonia', 'Macedonian denar', 'DEN', 'MKD', 'Deni', 100);
INSERT INTO currency () VALUES ('Northern Cyprus', 'Turkish lira', '₺', 'TRY', 'Kuruş', 100);
INSERT INTO currency () VALUES ('Norway', 'Norwegian krone', 'kr', 'NOK', 'Øre', 100);
INSERT INTO currency () VALUES ('Oman', 'Omani rial', 'RO', 'OMR', 'Baisa', 1000);
INSERT INTO currency () VALUES ('Pakistan', 'Pakistani rupee', 'Re or Rs (pl.)', 'PKR', 'Paisa', 100);
INSERT INTO currency () VALUES ('Palau', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Palestine', 'Israeli new shekel', '₪', 'ILS', 'Agora', 100);
INSERT INTO currency () VALUES ('Palestine', 'Jordanian dinar', 'JD', 'JOD', 'Piastre', 100);
INSERT INTO currency () VALUES ('Panama', 'Panamanian balboa', 'B/', 'PAB', 'Centésimo', 100);
INSERT INTO currency () VALUES ('Panama', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Papua New Guinea', 'Papua New Guinean kina', 'K', 'PGK', 'Toea', 100);
INSERT INTO currency () VALUES ('Paraguay', 'Paraguayan guaraní', '₲', 'PYG', 'Céntimo', 100);
INSERT INTO currency () VALUES ('Peru', 'Peruvian sol', 'S/', 'PEN', 'Céntimo', 100);
INSERT INTO currency () VALUES ('Philippines', 'Philippine peso', '₱', 'PHP', 'Sentimo', 100);
INSERT INTO currency () VALUES ('Pitcairn Islands', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO currency () VALUES ('Pitcairn Islands', 'Pitcairn Islands dollar', '$', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('Poland', 'Polish złoty', 'zł', 'PLN', 'Grosz', 100);
INSERT INTO currency () VALUES ('Portugal', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Qatar', 'Qatari riyal', 'QR', 'QAR', 'Dirham', 100);
INSERT INTO currency () VALUES ('Romania', 'Romanian leu', 'Leu or Lei (pl.)', 'RON', 'Ban', 100);
INSERT INTO currency () VALUES ('Russia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO currency () VALUES ('Rwanda', 'Rwandan franc', 'Fr', 'RWF', 'Centime', 100);
INSERT INTO currency () VALUES ('Saba', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Sahrawi Republic', 'Algerian dinar', 'DA', 'DZD', 'Santeem', 100);
INSERT INTO currency () VALUES ('Sahrawi Republic', 'Mauritanian ouguiya', 'UM', 'MRU', 'Khoums', 5);
INSERT INTO currency () VALUES ('Sahrawi Republic', 'Moroccan dirham', 'DH', 'MAD', 'Centime', 100);
INSERT INTO currency () VALUES ('Sahrawi Republic', 'Sahrawi peseta', 'Pta or Pts (pl.)', NULL, 'Centime', 100);
INSERT INTO currency () VALUES ('Saint Helena', 'Saint Helena pound', '£', 'SHP', 'Penny', 100);
INSERT INTO currency () VALUES ('Saint Kitts and Nevis', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Saint Lucia', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Saint Vincent and the Grenadines', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO currency () VALUES ('Samoa', 'Samoan tālā', '$', 'WST', 'Sene', 100);
INSERT INTO currency () VALUES ('San Marino', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('São Tomé and Príncipe', 'São Tomé and Príncipe dobra', 'Db', 'STN', 'Cêntimo', 100);
INSERT INTO currency () VALUES ('Saudi Arabia', 'Saudi riyal', 'Rl or Rls (pl.)', 'SAR', 'Halala', 100);
INSERT INTO currency () VALUES ('Senegal', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Serbia', 'Serbian dinar', 'DIN', 'RSD', 'Para', 100);
INSERT INTO currency () VALUES ('Seychelles', 'Seychellois rupee', 'Re or Rs (pl.)', 'SCR', 'Cent', 100);
INSERT INTO currency () VALUES ('Sierra Leone', 'Sierra Leonean leone', 'Le', 'SLE', 'Cent', 100);
INSERT INTO currency () VALUES ('Singapore', 'Singapore dollar', '$', 'SGD', 'Cent', 100);
INSERT INTO currency () VALUES ('Singapore', 'Brunei dollar', '$', 'BND', 'Sen', 100);
INSERT INTO currency () VALUES ('Sint Eustatius', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Sint Maarten', 'Netherlands Antillean guilder', 'ƒ', 'ANG', 'Cent', 100);
INSERT INTO currency () VALUES ('Slovakia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Slovenia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Solomon Islands', 'Solomon Islands dollar', '$', 'SBD', 'Cent', 100);
INSERT INTO currency () VALUES ('Somalia', 'Somali shilling', 'Sh or Shs (pl.)', 'SOS', 'Cent', 100);
INSERT INTO currency () VALUES ('Somaliland', 'Somaliland shilling', 'Sh or Shs (pl.)', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('South Africa', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO currency () VALUES ('South Ossetia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO currency () VALUES ('Spain', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('South Sudan', 'South Sudanese pound', NULL, 'SSP', 'Piaster', 100);
INSERT INTO currency () VALUES ('Sri Lanka', 'Sri Lankan rupee', 'Re or Rs (pl.)', 'LKR', 'Cent', 100);
INSERT INTO currency () VALUES ('Sudan', 'Sudanese pound', 'LS', 'SDG', 'Piastre', 100);
INSERT INTO currency () VALUES ('Suriname', 'Surinamese dollar', '$', 'SRD', 'Cent', 100);
INSERT INTO currency () VALUES ('Sweden', 'Swedish krona', 'kr', 'SEK', 'Öre', 100);
INSERT INTO currency () VALUES ('Switzerland', 'Swiss franc', 'Fr', 'CHF', 'Rappen', 100);
INSERT INTO currency () VALUES ('Syria', 'Syrian pound', 'LS', 'SYP', 'Piastre', 100);
INSERT INTO currency () VALUES ('Taiwan, Republic of China', 'New Taiwan dollar', '$', 'TWD', 'Cent', 100);
INSERT INTO currency () VALUES ('Tajikistan', 'Tajikistani somoni', 'SM', 'TJS', 'Diram', 100);
INSERT INTO currency () VALUES ('Tanzania', 'Tanzanian shilling', 'Sh or Shs (pl.)', 'TZS', 'Cent', 100);
INSERT INTO currency () VALUES ('Thailand', 'Thai baht', '฿', 'THB', 'Satang', 100);
INSERT INTO currency () VALUES ('Togo', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO currency () VALUES ('Tonga', 'Tongan paʻanga', 'T$', 'TOP', 'Seniti', 100);
INSERT INTO currency () VALUES ('Transnistria', 'Transnistrian ruble', 'р', NULL, 'Kopeck', 100);
INSERT INTO currency () VALUES ('Trinidad and Tobago', 'Trinidad and Tobago dollar', '$', 'TTD', 'Cent', 100);
INSERT INTO currency () VALUES ('Tunisia', 'Tunisian dinar', 'DT', 'TND', 'Millime', 1000);
INSERT INTO currency () VALUES ('Turkey', 'Turkish lira', '₺', 'TRY', 'Kuruş', 100);
INSERT INTO currency () VALUES ('Turkmenistan', 'Turkmenistani manat', 'm', 'TMT', 'Tenge', 100);
INSERT INTO currency () VALUES ('Turks and Caicos Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Tuvalu', 'Tuvaluan dollar', '$', NULL, 'Cent', 100);
INSERT INTO currency () VALUES ('Tuvalu', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO currency () VALUES ('Uganda', 'Ugandan shilling', 'Sh or Shs (pl.)', 'UGX', NULL, (none));
INSERT INTO currency () VALUES ('Ukraine', 'Ukrainian hryvnia', '₴', 'UAH', 'Kopeck', 100);
INSERT INTO currency () VALUES ('United Arab Emirates', 'United Arab Emirates dirham', 'Dh or Dhs (pl.)', 'AED', 'Fils', 100);
INSERT INTO currency () VALUES ('United Kingdom', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO currency () VALUES ('United States', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO currency () VALUES ('Uruguay', 'Uruguayan peso', '$', 'UYU', 'Centésimo', 100);
INSERT INTO currency () VALUES ('Uzbekistan', 'Uzbekistani soum', 'soum', 'UZS', 'Tiyin', 100);
INSERT INTO currency () VALUES ('Vanuatu', 'Vanuatu vatu', 'VT', 'VUV', 'Cent', 100);
INSERT INTO currency () VALUES ('Vatican City', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO currency () VALUES ('Venezuela', 'Venezuelan sovereign bolívar', 'Bs.S', 'VES', 'Céntimo', 100);
INSERT INTO currency () VALUES ('Venezuela', 'Venezuelan digital bolívar', 'Bs.D', 'VED', 'Céntimo', 100);
INSERT INTO currency () VALUES ('Vietnam', 'Vietnamese đồng', '₫', 'VND', 'Hào', 10);
INSERT INTO currency () VALUES ('Wallis and Futuna', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO currency () VALUES ('Yemen', 'Yemeni rial', 'Rl or Rls (pl.)', 'YER', 'Fils', 100);
INSERT INTO currency () VALUES ('Zambia', 'Zambian kwacha', 'K', 'ZMW', 'Ngwee', 100);
INSERT INTO currency () VALUES ('Zimbabwe', 'RTGS dollar', '$', NULL, 'Cent', 100);
