INSERT INTO gdp () VALUES ('Afghanistan', 20136);
INSERT INTO gdp () VALUES ('Albania', 18256);
INSERT INTO gdp () VALUES ('Algeria', 187155);
INSERT INTO gdp () VALUES ('American Samoa', NULL);
INSERT INTO gdp () VALUES ('Andorra', 3302);
INSERT INTO gdp () VALUES ('Angola', 124794);
INSERT INTO gdp () VALUES ('Anguilla', NULL);
INSERT INTO gdp () VALUES ('Antigua and Barbuda', 1692);
INSERT INTO gdp () VALUES ('Argentina', 630698);
INSERT INTO gdp () VALUES ('Armenia', 17693);
INSERT INTO gdp () VALUES ('Aruba', 3499);
INSERT INTO gdp () VALUES ('Australia', 1724787);
INSERT INTO gdp () VALUES ('Austria', 468046);
INSERT INTO gdp () VALUES ('Azerbaijan', 70066);
INSERT INTO gdp () VALUES ('Bahamas', 12693);
INSERT INTO gdp () VALUES ('Bahrain', 43544);
INSERT INTO gdp () VALUES ('Bangladesh', 460751);
INSERT INTO gdp () VALUES ('Barbados', 5788);
INSERT INTO gdp () VALUES ('Belarus', 79704);
INSERT INTO gdp () VALUES ('Belgium', 589491);
INSERT INTO gdp () VALUES ('Belize', 2676);
INSERT INTO gdp () VALUES ('Benin', 17547);
INSERT INTO gdp () VALUES ('Bermuda', NULL);
INSERT INTO gdp () VALUES ('Bhutan', 2707);
INSERT INTO gdp () VALUES ('Bolivia', 43431);
INSERT INTO gdp () VALUES ('Bosnia and Herzegovina', 23681);
INSERT INTO gdp () VALUES ('Botswana', 18005);
INSERT INTO gdp () VALUES ('Brazil', 1894708);
INSERT INTO gdp () VALUES ('British Virgin Islands', NULL);
INSERT INTO gdp () VALUES ('Brunei', 18464);
INSERT INTO gdp () VALUES ('Bulgaria', 85008);
INSERT INTO gdp () VALUES ('Burkina Faso', 18268);
INSERT INTO gdp () VALUES ('Burundi', 3686);
INSERT INTO gdp () VALUES ('Cambodia', 28330);
INSERT INTO gdp () VALUES ('Cameroon', 44212);
INSERT INTO gdp () VALUES ('Canada', 2200352);
INSERT INTO gdp () VALUES ('Cape Verde', 2053);
INSERT INTO gdp () VALUES ('Cayman Islands', NULL);
INSERT INTO gdp () VALUES ('Central African Republic', 2488);
INSERT INTO gdp () VALUES ('Chad', 12945);
INSERT INTO gdp () VALUES ('Chile', 310866);
INSERT INTO gdp () VALUES ('China', 18321197);
INSERT INTO gdp () VALUES ('Colombia', 342919);
INSERT INTO gdp () VALUES ('Comoros', 1242);
INSERT INTO gdp () VALUES ('Congo', 14486);
INSERT INTO gdp () VALUES ('Cook Islands', NULL);
INSERT INTO gdp () VALUES ('Costa Rica', 68489);
INSERT INTO gdp () VALUES ('Croatia', 69380);
INSERT INTO gdp () VALUES ('Cuba', NULL);
INSERT INTO gdp () VALUES ('Curaçao', NULL);
INSERT INTO gdp () VALUES ('Cyprus', 26705);
INSERT INTO gdp () VALUES ('Czech Republic', 295618);
INSERT INTO gdp () VALUES ('DR Congo', 63909);
INSERT INTO gdp () VALUES ('Denmark', 386724);
INSERT INTO gdp () VALUES ('Djibouti', 3725);
INSERT INTO gdp () VALUES ('Dominica', 599);
INSERT INTO gdp () VALUES ('Dominican Republic', 112417);
INSERT INTO gdp () VALUES ('East Timor', 2455);
INSERT INTO gdp () VALUES ('Ecuador', 115469);
INSERT INTO gdp () VALUES ('Egypt', 469094);
INSERT INTO gdp () VALUES ('El Salvador', 31989);
INSERT INTO gdp () VALUES ('Equatorial Guinea', 16877);
INSERT INTO gdp () VALUES ('Eritrea', 2369);
INSERT INTO gdp () VALUES ('Estonia', 39054);
INSERT INTO gdp () VALUES ('Eswatini', 4669);
INSERT INTO gdp () VALUES ('Ethiopia', 111181);
INSERT INTO gdp () VALUES ('Fiji', 4859);
INSERT INTO gdp () VALUES ('Finland', 281411);
INSERT INTO gdp () VALUES ('France', 2778090);
INSERT INTO gdp () VALUES ('French Polynesia', NULL);
INSERT INTO gdp () VALUES ('Gabon', 22221);
INSERT INTO gdp () VALUES ('Gambia', 2172);
INSERT INTO gdp () VALUES ('Georgia', 25172);
INSERT INTO gdp () VALUES ('Germany', 4031149);
INSERT INTO gdp () VALUES ('Ghana', 75996);
INSERT INTO gdp () VALUES ('Greece', 222008);
INSERT INTO gdp () VALUES ('Greenland', NULL);
INSERT INTO gdp () VALUES ('Grenada', 1192);
INSERT INTO gdp () VALUES ('Guam', NULL);
INSERT INTO gdp () VALUES ('Guatemala', 91318);
INSERT INTO gdp () VALUES ('Guinea', 19745);
INSERT INTO gdp () VALUES ('Guinea-Bissau', 1624);
INSERT INTO gdp () VALUES ('Guyana', 14839);
INSERT INTO gdp () VALUES ('Haiti', 20182);
INSERT INTO gdp () VALUES ('Honduras', 30568);
INSERT INTO gdp () VALUES ('Hong Kong', 368373);
INSERT INTO gdp () VALUES ('Hungary', 184651);
INSERT INTO gdp () VALUES ('Iceland', 27702);
INSERT INTO gdp () VALUES ('India', 3468566);
INSERT INTO gdp () VALUES ('Indonesia', 1289429);
INSERT INTO gdp () VALUES ('Iran', 1973738);
INSERT INTO gdp () VALUES ('Iraq', 282876);
INSERT INTO gdp () VALUES ('Ireland', 519776);
INSERT INTO gdp () VALUES ('Israel', 527179);
INSERT INTO gdp () VALUES ('Italy', 1996934);
INSERT INTO gdp () VALUES ('Ivory Coast', 68630);
INSERT INTO gdp () VALUES ('Jamaica', 16104);
INSERT INTO gdp () VALUES ('Japan', 4300621);
INSERT INTO gdp () VALUES ('Jordan', 48066);
INSERT INTO gdp () VALUES ('Kazakhstan', 224338);
INSERT INTO gdp () VALUES ('Kenya', 114858);
INSERT INTO gdp () VALUES ('Kiribati', 207);
INSERT INTO gdp () VALUES ('Kosovo', 9242);
INSERT INTO gdp () VALUES ('Kuwait', 183568);
INSERT INTO gdp () VALUES ('Kyrgyzstan', 9750);
INSERT INTO gdp () VALUES ('Laos', 16250);
INSERT INTO gdp () VALUES ('Latvia', 40588);
INSERT INTO gdp () VALUES ('Lebanon', 24494);
INSERT INTO gdp () VALUES ('Lesotho', 2507);
INSERT INTO gdp () VALUES ('Liberia', 3900);
INSERT INTO gdp () VALUES ('Libya', 40836);
INSERT INTO gdp () VALUES ('Liechtenstein', NULL);
INSERT INTO gdp () VALUES ('Lithuania', 68031);
INSERT INTO gdp () VALUES ('Luxembourg', 82154);
INSERT INTO gdp () VALUES ('Macau', 23420);
INSERT INTO gdp () VALUES ('Madagascar', 15106);
INSERT INTO gdp () VALUES ('Malawi', 11554);
INSERT INTO gdp () VALUES ('Malaysia', 434059);
INSERT INTO gdp () VALUES ('Maldives', 5900);
INSERT INTO gdp () VALUES ('Mali', 18434);
INSERT INTO gdp () VALUES ('Malta', 17156);
INSERT INTO gdp () VALUES ('Marshall Islands', 271);
INSERT INTO gdp () VALUES ('Mauritania', 10091);
INSERT INTO gdp () VALUES ('Mauritius', 11497);
INSERT INTO gdp () VALUES ('Mexico', 1424533);
INSERT INTO gdp () VALUES ('Micronesia', 428);
INSERT INTO gdp () VALUES ('Moldova', 14048);
INSERT INTO gdp () VALUES ('Monaco', NULL);
INSERT INTO gdp () VALUES ('Mongolia', 15720);
INSERT INTO gdp () VALUES ('Montenegro', 6127);
INSERT INTO gdp () VALUES ('Montserrat', NULL);
INSERT INTO gdp () VALUES ('Morocco', 142874);
INSERT INTO gdp () VALUES ('Mozambique', 17873);
INSERT INTO gdp () VALUES ('Myanmar', 59530);
INSERT INTO gdp () VALUES ('Namibia', 12488);
INSERT INTO gdp () VALUES ('Nauru', 134);
INSERT INTO gdp () VALUES ('Nepal', 39028);
INSERT INTO gdp () VALUES ('Netherlands', 990583);
INSERT INTO gdp () VALUES ('New Caledonia', NULL);
INSERT INTO gdp () VALUES ('New Zealand', 242700);
INSERT INTO gdp () VALUES ('Nicaragua', 15695);
INSERT INTO gdp () VALUES ('Niger', 14639);
INSERT INTO gdp () VALUES ('Nigeria', 504203);
INSERT INTO gdp () VALUES ('North Korea', NULL);
INSERT INTO gdp () VALUES ('North Macedonia', 14101);
INSERT INTO gdp () VALUES ('Northern Mariana Islands', NULL);
INSERT INTO gdp () VALUES ('Norway', 504703);
INSERT INTO gdp () VALUES ('Oman', 108969);
INSERT INTO gdp () VALUES ('Pakistan', 376493);
INSERT INTO gdp () VALUES ('Palau', 226);
INSERT INTO gdp () VALUES ('Palestine', 19698);
INSERT INTO gdp () VALUES ('Panama', 71085);
INSERT INTO gdp () VALUES ('Papua New Guinea', 31362);
INSERT INTO gdp () VALUES ('Paraguay', 41855);
INSERT INTO gdp () VALUES ('Peru', 239333);
INSERT INTO gdp () VALUES ('Philippines', 401662);
INSERT INTO gdp () VALUES ('Poland', 716305);
INSERT INTO gdp () VALUES ('Portugal', 255854);
INSERT INTO gdp () VALUES ('Puerto Rico', 118677);
INSERT INTO gdp () VALUES ('Qatar', 221369);
INSERT INTO gdp () VALUES ('Romania', 299885);
INSERT INTO gdp () VALUES ('Russia', 2133092);
INSERT INTO gdp () VALUES ('Rwanda', 12098);
INSERT INTO gdp () VALUES ('Saint Kitts and Nevis', 1115);
INSERT INTO gdp () VALUES ('Saint Lucia', 1972);
INSERT INTO gdp () VALUES ('Saint Vincent and the Grenadines', 948);
INSERT INTO gdp () VALUES ('Samoa', 830);
INSERT INTO gdp () VALUES ('San Marino', 1623);
INSERT INTO gdp () VALUES ('Saudi Arabia', 1010588);
INSERT INTO gdp () VALUES ('Senegal', 27542);
INSERT INTO gdp () VALUES ('Serbia', 62721);
INSERT INTO gdp () VALUES ('Seychelles', 2005);
INSERT INTO gdp () VALUES ('Sierra Leone', 4101);
INSERT INTO gdp () VALUES ('Singapore', 423632);
INSERT INTO gdp () VALUES ('Sint Maarten', NULL);
INSERT INTO gdp () VALUES ('Slovakia', 112418);
INSERT INTO gdp () VALUES ('Slovenia', 62191);
INSERT INTO gdp () VALUES ('Solomon Islands', 1601);
INSERT INTO gdp () VALUES ('Somalia', 8416);
INSERT INTO gdp () VALUES ('South Africa', 411480);
INSERT INTO gdp () VALUES ('South Korea', 1734207);
INSERT INTO gdp () VALUES ('South Sudan', 4784);
INSERT INTO gdp () VALUES ('Spain', 1389927);
INSERT INTO gdp () VALUES ('Sri Lanka', 73739);
INSERT INTO gdp () VALUES ('Sudan', 42762);
INSERT INTO gdp () VALUES ('Suriname', 3011);
INSERT INTO gdp () VALUES ('Sweden', 603922);
INSERT INTO gdp () VALUES ('Switzerland', 807418);
INSERT INTO gdp () VALUES ('Syria', NULL);
INSERT INTO gdp () VALUES ('São Tomé and Príncipe', 506);
INSERT INTO gdp () VALUES ('Taiwan', 828659);
INSERT INTO gdp () VALUES ('Tajikistan', 9983);
INSERT INTO gdp () VALUES ('Tanzania', 76582);
INSERT INTO gdp () VALUES ('Thailand', 534758);
INSERT INTO gdp () VALUES ('Togo', 8359);
INSERT INTO gdp () VALUES ('Tonga', 501);
INSERT INTO gdp () VALUES ('Trinidad and Tobago', 29337);
INSERT INTO gdp () VALUES ('Tunisia', 46282);
INSERT INTO gdp () VALUES ('Turkey', 853487);
INSERT INTO gdp () VALUES ('Turkmenistan', 74439);
INSERT INTO gdp () VALUES ('Turks and Caicos Islands', NULL);
INSERT INTO gdp () VALUES ('Tuvalu', 64);
INSERT INTO gdp () VALUES ('Uganda', 48352);
INSERT INTO gdp () VALUES ('Ukraine', 199719);
INSERT INTO gdp () VALUES ('United Arab Emirates', 503913);
INSERT INTO gdp () VALUES ('United Kingdom', 3198470);
INSERT INTO gdp () VALUES ('United States', 25035164);
INSERT INTO gdp () VALUES ('Uruguay', 71161);
INSERT INTO gdp () VALUES ('Uzbekistan', 79117);
INSERT INTO gdp () VALUES ('Vanuatu', 984);
INSERT INTO gdp () VALUES ('Venezuela', 82145);
INSERT INTO gdp () VALUES ('Vietnam', 413808);
INSERT INTO gdp () VALUES ('Yemen', 27594);
INSERT INTO gdp () VALUES ('Zambia', 27025);
INSERT INTO gdp () VALUES ('Zanzibar', NULL);
INSERT INTO gdp () VALUES ('Zimbabwe', 38280);
