INSERT INTO head_of_state () VALUES ('Abkhazia', 'President – Aslan Bzhania');
INSERT INTO head_of_state () VALUES ('Afghanistan', 'Supreme Leader – Hibatullah Akhundzada');
INSERT INTO head_of_state () VALUES ('Albania', 'President – Bajram Begaj');
INSERT INTO head_of_state () VALUES ('Algeria', 'President – Abdelmadjid Tebboune');
INSERT INTO head_of_state () VALUES ('Andorra', 'Episcopal Co-Prince – Joan Enric Vives i Sicília\nCo-Prince''s Representative – Josep Maria Mauri\nFrench Co-Prince – Emmanuel Macron\nCo-Prince''s Representative – Patrick Strzoda');
INSERT INTO head_of_state () VALUES ('Angola', 'President – João Lourenço');
INSERT INTO head_of_state () VALUES ('Antigua and Barbuda', 'King – Charles III\nGovernor-General – Sir Rodney Williams');
INSERT INTO head_of_state () VALUES ('Argentina', 'President – Alberto Fernández');
INSERT INTO head_of_state () VALUES ('Armenia', 'President – Vahagn Khachaturyan');
INSERT INTO head_of_state () VALUES ('Australia', 'King – Charles III\nGovernor-General – David Hurley');
INSERT INTO head_of_state () VALUES ('Austria', 'President – Alexander Van der Bellen');
INSERT INTO head_of_state () VALUES ('Azerbaijan', 'President – Ilham Aliyev');
INSERT INTO head_of_state () VALUES ('Bahamas, The', 'King – Charles III\nGovernor-General – Sir Cornelius A. Smith');
INSERT INTO head_of_state () VALUES ('Bahrain', 'King – Sheikh Hamad bin Isa Al Khalifa');
INSERT INTO head_of_state () VALUES ('Bangladesh', 'President – Abdul Hamid');
INSERT INTO head_of_state () VALUES ('Barbados', 'President – Dame Sandra Mason');
INSERT INTO head_of_state () VALUES ('Belarus', 'President – Alexander Lukashenko');
INSERT INTO head_of_state () VALUES ('Belgium', 'King – Philippe');
INSERT INTO head_of_state () VALUES ('Belize', 'King – Charles III\nGovernor-General – Dame Froyla Tzalam');
INSERT INTO head_of_state () VALUES ('Benin', 'President – Patrice Talon');
INSERT INTO head_of_state () VALUES ('Bhutan', 'King – Jigme Khesar Namgyel Wangchuck');
INSERT INTO head_of_state () VALUES ('Bolivia', 'President – Luis Arce');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'High Representative – Christian Schmidt');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Presidency');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Željka Cvijanović (as Chairwoman)');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Denis Bećirović (as Member)\nŽeljko Komšić (as Member)');
INSERT INTO head_of_state () VALUES ('Botswana', 'President – Mokgweetsi Masisi');
INSERT INTO head_of_state () VALUES ('Brazil', 'President – Jair Bolsonaro');
INSERT INTO head_of_state () VALUES ('Brazil', 'President-elect – Luiz Inácio Lula da Silva');
INSERT INTO head_of_state () VALUES ('Brunei', 'Sultan and Prime Minister – Hassanal Bolkiah');
INSERT INTO head_of_state () VALUES ('Bulgaria', 'President – Rumen Radev');
INSERT INTO head_of_state () VALUES ('Burkina Faso', 'President of the Patriotic Movement for Safeguard and Restoration – Ibrahim Traoré');
INSERT INTO head_of_state () VALUES ('Burkina Faso', 'Interim President – Ibrahim Traoré');
INSERT INTO head_of_state () VALUES ('Burundi', 'President – Évariste Ndayishimiye');
INSERT INTO head_of_state () VALUES ('Cambodia', 'King – Norodom Sihamoni');
INSERT INTO head_of_state () VALUES ('Cameroon', 'President – Paul Biya');
INSERT INTO head_of_state () VALUES ('Canada', 'King – Charles III\nGovernor General – Mary Simon');
INSERT INTO head_of_state () VALUES ('Cape Verde', 'President – José Maria Neves');
INSERT INTO head_of_state () VALUES ('Central African Republic', 'President – Faustin-Archange Touadéra');
INSERT INTO head_of_state () VALUES ('Chad', 'Transitional President – Mahamat Déby');
INSERT INTO head_of_state () VALUES ('Chile', 'President – Gabriel Boric');
INSERT INTO head_of_state () VALUES ('China', 'General Secretary of the Communist Party – Xi Jinping');
INSERT INTO head_of_state () VALUES ('China', 'President – Xi Jinping');
INSERT INTO head_of_state () VALUES ('Colombia', 'President – Gustavo Petro');
INSERT INTO head_of_state () VALUES ('Comoros', 'President – Azali Assoumani');
INSERT INTO head_of_state () VALUES ('Congo, Democratic Republic of the', 'President – Félix Tshisekedi');
INSERT INTO head_of_state () VALUES ('Congo, Republic of the', 'President – Denis Sassou Nguesso');
INSERT INTO head_of_state () VALUES ('Cook Islands', 'King – Charles III\nKing''s Representative – Sir Tom Marsters');
INSERT INTO head_of_state () VALUES ('Costa Rica', 'President – Rodrigo Chaves Robles');
INSERT INTO head_of_state () VALUES ('Croatia', 'President – Zoran Milanović');
INSERT INTO head_of_state () VALUES ('Cuba', 'First Secretary of the Communist Party – Miguel Díaz-Canel');
INSERT INTO head_of_state () VALUES ('Cuba', 'President – Miguel Díaz-Canel');
INSERT INTO head_of_state () VALUES ('Cyprus', 'President – Nicos Anastasiades');
INSERT INTO head_of_state () VALUES ('Czech Republic', 'President – Miloš Zeman');
INSERT INTO head_of_state () VALUES ('Denmark', 'Queen – Margrethe II');
INSERT INTO head_of_state () VALUES ('Djibouti', 'President – Ismaïl Omar Guelleh');
INSERT INTO head_of_state () VALUES ('Dominica', 'President – Charles Savarin');
INSERT INTO head_of_state () VALUES ('Dominican Republic', 'President – Luis Abinader');
INSERT INTO head_of_state () VALUES ('East Timor', 'President – José Ramos-Horta');
INSERT INTO head_of_state () VALUES ('Ecuador', 'President – Guillermo Lasso');
INSERT INTO head_of_state () VALUES ('Egypt', 'President – Abdel Fattah el-Sisi');
INSERT INTO head_of_state () VALUES ('El Salvador', 'President – Nayib Bukele');
INSERT INTO head_of_state () VALUES ('Equatorial Guinea', 'President – Teodoro Obiang Nguema Mbasogo');
INSERT INTO head_of_state () VALUES ('Eritrea', 'Chairman of the People''s Front for Democracy and Justice – Isaias Afwerki');
INSERT INTO head_of_state () VALUES ('Eritrea', 'President – Isaias Afwerki');
INSERT INTO head_of_state () VALUES ('Estonia', 'President – Alar Karis');
INSERT INTO head_of_state () VALUES ('Eswatini', 'King – Mswati III');
INSERT INTO head_of_state () VALUES ('Ethiopia', 'President – Sahle-Work Zewde');
INSERT INTO head_of_state () VALUES ('Federated States of Micronesia', 'President – David W. Panuelo');
INSERT INTO head_of_state () VALUES ('Fiji', 'President – Ratu Wiliame Katonivere');
INSERT INTO head_of_state () VALUES ('Finland', 'President – Sauli Niinistö');
INSERT INTO head_of_state () VALUES ('France', 'President – Emmanuel Macron');
INSERT INTO head_of_state () VALUES ('Gabon', 'President – Ali Bongo Ondimba');
INSERT INTO head_of_state () VALUES ('Gambia, The', 'President – Adama Barrow');
INSERT INTO head_of_state () VALUES ('Georgia', 'President – Salome Zourabichvili');
INSERT INTO head_of_state () VALUES ('Germany', 'President – Frank-Walter Steinmeier');
INSERT INTO head_of_state () VALUES ('Ghana', 'President – Nana Akufo-Addo');
INSERT INTO head_of_state () VALUES ('Greece', 'President – Katerina Sakellaropoulou');
INSERT INTO head_of_state () VALUES ('Grenada', 'King – Charles III\nGovernor-General – Dame Cécile La Grenade');
INSERT INTO head_of_state () VALUES ('Guatemala', 'President – Alejandro Giammattei');
INSERT INTO head_of_state () VALUES ('Guinea', 'Chairman of the National Committee of Reconciliation and Development – Mamady Doumbouya');
INSERT INTO head_of_state () VALUES ('Guinea', 'Interim President – Mamady Doumbouya');
INSERT INTO head_of_state () VALUES ('Guinea-Bissau', 'President – Umaro Sissoco Embaló');
INSERT INTO head_of_state () VALUES ('Guyana', 'President – Irfaan Ali');
INSERT INTO head_of_state () VALUES ('Haiti', 'Interim President – Ariel Henry');
INSERT INTO head_of_state () VALUES ('Honduras', 'President – Xiomara Castro');
INSERT INTO head_of_state () VALUES ('Hungary', 'President – Katalin Novák');
INSERT INTO head_of_state () VALUES ('Iceland', 'President – Guðni Th. Jóhannesson');
INSERT INTO head_of_state () VALUES ('India', 'President – Droupadi Murmu');
INSERT INTO head_of_state () VALUES ('Indonesia', 'President – Joko Widodo');
INSERT INTO head_of_state () VALUES ('Iran', 'Supreme Leader – Ali Khamenei');
INSERT INTO head_of_state () VALUES ('Iraq', 'President – Abdul Latif Rashid');
INSERT INTO head_of_state () VALUES ('Ireland', 'President – Michael D. Higgins');
INSERT INTO head_of_state () VALUES ('Ireland', 'President – Michael D. Higgins');
INSERT INTO head_of_state () VALUES ('Israel', 'President – Isaac Herzog');
INSERT INTO head_of_state () VALUES ('Israel', 'President – Isaac Herzog');
INSERT INTO head_of_state () VALUES ('Italy', 'President – Sergio Mattarella');
INSERT INTO head_of_state () VALUES ('Ivory Coast', 'President – Alassane Ouattara');
INSERT INTO head_of_state () VALUES ('Jamaica', 'King – Charles III\nGovernor-General – Sir Patrick Allen');
INSERT INTO head_of_state () VALUES ('Japan', 'Emperor – Naruhito');
INSERT INTO head_of_state () VALUES ('Jordan', 'King – Abdullah II');
INSERT INTO head_of_state () VALUES ('Kazakhstan', 'President – Qasym-Zhomart Toqaev');
INSERT INTO head_of_state () VALUES ('Kenya', 'President – William Ruto');
INSERT INTO head_of_state () VALUES ('Kiribati', 'President – Taneti Maamau');
INSERT INTO head_of_state () VALUES ('Kosovo', 'President – Vjosa Osmani');
INSERT INTO head_of_state () VALUES ('Kuwait', 'Emir – Sheikh Nawaf Al-Ahmad Al-Jaber Al-Sabah');
INSERT INTO head_of_state () VALUES ('Kyrgyzstan', 'President – Sadyr Japarov');
INSERT INTO head_of_state () VALUES ('Laos', 'General Secretary of the People''s Revolutionary Party – Thongloun Sisoulith');
INSERT INTO head_of_state () VALUES ('Laos', 'President – Thongloun Sisoulith');
INSERT INTO head_of_state () VALUES ('Latvia', 'President – Egils Levits');
INSERT INTO head_of_state () VALUES ('Lebanon', 'Acting President – Najib Mikati');
INSERT INTO head_of_state () VALUES ('Lesotho', 'King – Letsie III');
INSERT INTO head_of_state () VALUES ('Liberia', 'President – George Weah');
INSERT INTO head_of_state () VALUES ('Libya', 'Chairman of the Presidential Council – Mohamed al-Menfi');
INSERT INTO head_of_state () VALUES ('Liechtenstein', 'Regent – Hereditary Prince Alois');
INSERT INTO head_of_state () VALUES ('Liechtenstein', 'Prince Regnant – Hans-Adam II');
INSERT INTO head_of_state () VALUES ('Lithuania', 'President – Gitanas Nausėda');
INSERT INTO head_of_state () VALUES ('Luxembourg', 'Grand Duke – Henri');
INSERT INTO head_of_state () VALUES ('Madagascar', 'President – Andry Rajoelina');
INSERT INTO head_of_state () VALUES ('Malawi', 'President – Lazarus Chakwera');
INSERT INTO head_of_state () VALUES ('Malaysia', 'Yang di-Pertuan Agong – Abdullah Sultan Ahmad Shah');
INSERT INTO head_of_state () VALUES ('Maldives', 'President – Ibrahim Mohamed Solih');
INSERT INTO head_of_state () VALUES ('Mali', 'Interim President – Assimi Goïta');
INSERT INTO head_of_state () VALUES ('Malta', 'President – George Vella');
INSERT INTO head_of_state () VALUES ('Marshall Islands', 'President – David Kabua');
INSERT INTO head_of_state () VALUES ('Mauritania', 'President – Mohamed Ould Ghazouani');
INSERT INTO head_of_state () VALUES ('Mauritius', 'President – Prithvirajsing Roopun');
INSERT INTO head_of_state () VALUES ('Mexico', 'President – Andrés Manuel López Obrador');
INSERT INTO head_of_state () VALUES ('Moldova', 'President – Maia Sandu');
INSERT INTO head_of_state () VALUES ('Monaco', 'Sovereign Prince – Albert II');
INSERT INTO head_of_state () VALUES ('Mongolia', 'President – Ukhnaagiin Khürelsükh');
INSERT INTO head_of_state () VALUES ('Montenegro', 'President – Milo Đukanović');
INSERT INTO head_of_state () VALUES ('Morocco', 'King – Mohammed VI');
INSERT INTO head_of_state () VALUES ('Mozambique', 'President – Filipe Nyusi');
INSERT INTO head_of_state () VALUES ('Myanmar', 'Chairman of the State Administration Council – Min Aung Hlaing');
INSERT INTO head_of_state () VALUES ('Myanmar', 'Acting President – Myint Swe');
INSERT INTO head_of_state () VALUES ('Namibia', 'President – Hage Geingob');
INSERT INTO head_of_state () VALUES ('Nauru', 'President – Russ Kun');
INSERT INTO head_of_state () VALUES ('Nepal', 'President – Bidya Devi Bhandari');
INSERT INTO head_of_state () VALUES ('Netherlands', 'King – Willem-Alexander');
INSERT INTO head_of_state () VALUES ('New Zealand', 'King – Charles III\nGovernor-General – Dame Cindy Kiro');
INSERT INTO head_of_state () VALUES ('Nicaragua', 'President – Daniel Ortega');
INSERT INTO head_of_state () VALUES ('Niger', 'President – Mohamed Bazoum');
INSERT INTO head_of_state () VALUES ('Nigeria', 'President – Muhammadu Buhari');
INSERT INTO head_of_state () VALUES ('Niue', 'King – Charles III\nKing''s Representative – Dame Cindy Kiro');
INSERT INTO head_of_state () VALUES ('North Korea', 'General Secretary of the Workers'' Party of Korea – Kim Jong-un');
INSERT INTO head_of_state () VALUES ('North Korea', 'President of the State Affairs Commission – Kim Jong-un');
INSERT INTO head_of_state () VALUES ('North Macedonia', 'President – Stevo Pendarovski');
INSERT INTO head_of_state () VALUES ('Northern Cyprus', 'President – Ersin Tatar');
INSERT INTO head_of_state () VALUES ('Norway', 'King – Harald V');
INSERT INTO head_of_state () VALUES ('Oman', 'Sultan and Prime Minister – Haitham bin Tariq');
INSERT INTO head_of_state () VALUES ('Pakistan', 'President – Arif Alvi');
INSERT INTO head_of_state () VALUES ('Palau', 'President – Surangel Whipps Jr.');
INSERT INTO head_of_state () VALUES ('Palestine', 'President – Mahmoud Abbas');
INSERT INTO head_of_state () VALUES ('Panama', 'President – Laurentino Cortizo');
INSERT INTO head_of_state () VALUES ('Papua New Guinea', 'King – Charles III\nGovernor-General – Sir Bob Dadae');
INSERT INTO head_of_state () VALUES ('Paraguay', 'President – Mario Abdo Benítez');
INSERT INTO head_of_state () VALUES ('Peru', 'President – Dina Boluarte');
INSERT INTO head_of_state () VALUES ('Philippines', 'President – Bongbong Marcos');
INSERT INTO head_of_state () VALUES ('Poland', 'President – Andrzej Duda');
INSERT INTO head_of_state () VALUES ('Portugal', 'President – Marcelo Rebelo de Sousa');
INSERT INTO head_of_state () VALUES ('Qatar', 'Emir – Sheikh Tamim bin Hamad Al Thani');
INSERT INTO head_of_state () VALUES ('Republic of China (Taiwan)', 'President – Tsai Ing-wen');
INSERT INTO head_of_state () VALUES ('Romania', 'President – Klaus Iohannis');
INSERT INTO head_of_state () VALUES ('Russia', 'President – Vladimir Putin');
INSERT INTO head_of_state () VALUES ('Rwanda', 'President – Paul Kagame');
INSERT INTO head_of_state () VALUES ('Sahrawi Republic', 'President – Brahim Ghali');
INSERT INTO head_of_state () VALUES ('Sahrawi Republic', 'General Secretary of the Polisario Front – Brahim Ghali');
INSERT INTO head_of_state () VALUES ('Saint Kitts and Nevis', 'King – Charles III\nGovernor-General – Sir Tapley Seaton');
INSERT INTO head_of_state () VALUES ('Saint Lucia', 'King – Charles III\nActing Governor-General – Errol Charles');
INSERT INTO head_of_state () VALUES ('Saint Vincent and the Grenadines', 'King – Charles III\nGovernor-General – Dame Susan Dougan');
INSERT INTO head_of_state () VALUES ('Samoa', 'O le Ao o le Malo – Afioga Tuimalealiʻifano Vaʻaletoʻa Sualauvi II');
INSERT INTO head_of_state () VALUES ('San Marino', 'Captain Regent – Maria Luisa Berti');
INSERT INTO head_of_state () VALUES ('San Marino', 'Captain Regent – Manuel Ciavatta');
INSERT INTO head_of_state () VALUES ('Saudi Arabia', 'King – Salman');
INSERT INTO head_of_state () VALUES ('Senegal', 'President – Macky Sall');
INSERT INTO head_of_state () VALUES ('Serbia', 'President – Aleksandar Vučić');
INSERT INTO head_of_state () VALUES ('Seychelles', 'President – Wavel Ramkalawan');
INSERT INTO head_of_state () VALUES ('Sierra Leone', 'President – Julius Maada Bio');
INSERT INTO head_of_state () VALUES ('Singapore', 'President – Halimah Yacob');
INSERT INTO head_of_state () VALUES ('Slovakia', 'President – Zuzana Čaputová');
INSERT INTO head_of_state () VALUES ('Slovenia', 'President – Borut Pahor\nPresident-elect – Nataša Pirc Musar');
INSERT INTO head_of_state () VALUES ('Solomon Islands', 'King – Charles III\nGovernor-General – Sir David Vunagi');
INSERT INTO head_of_state () VALUES ('Somalia', 'President – Hassan Sheikh Mohamud');
INSERT INTO head_of_state () VALUES ('South Africa', 'President – Cyril Ramaphosa');
INSERT INTO head_of_state () VALUES ('South Korea', 'President – Yoon Suk-yeol');
INSERT INTO head_of_state () VALUES ('South Ossetia', 'President – Alan Gagloyev');
INSERT INTO head_of_state () VALUES ('South Sudan', 'President – Salva Kiir Mayardit');
INSERT INTO head_of_state () VALUES ('Spain', 'King – Felipe VI');
INSERT INTO head_of_state () VALUES ('Sri Lanka', 'President – Ranil Wickremesinghe');
INSERT INTO head_of_state () VALUES ('Sudan', 'Chairman of the Transitional Sovereignty Council – Abdel Fattah al-Burhan');
INSERT INTO head_of_state () VALUES ('Suriname', 'President – Chan Santokhi');
INSERT INTO head_of_state () VALUES ('Sweden', 'King – Carl XVI Gustaf');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Members: \nIgnazio Cassis (President)\nAlain Berset (Vice President)\nUeli Maurer\nSimonetta Sommaruga\nGuy Parmelin\nKarin Keller-Sutter\nViola Amherd');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Federal Council');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Members-elect of the Federal Council: \nAlbert Rösti\nÉlisabeth Baume-Schneider');
INSERT INTO head_of_state () VALUES ('Syria', 'President – Bashar al-Assad');
INSERT INTO head_of_state () VALUES ('São Tomé and Príncipe', 'President – Carlos Vila Nova');
INSERT INTO head_of_state () VALUES ('Tajikistan', 'President – Emomali Rahmon');
INSERT INTO head_of_state () VALUES ('Tanzania', 'President – Samia Suluhu Hassan');
INSERT INTO head_of_state () VALUES ('Thailand', 'King – Maha Vajiralongkorn');
INSERT INTO head_of_state () VALUES ('Togo', 'President – Faure Gnassingbé');
INSERT INTO head_of_state () VALUES ('Tonga', 'King – Tupou VI');
INSERT INTO head_of_state () VALUES ('Trinidad and Tobago', 'President – Paula-Mae Weekes');
INSERT INTO head_of_state () VALUES ('Tunisia', 'President – Kaïs Saïed');
INSERT INTO head_of_state () VALUES ('Turkey', 'President – Recep Tayyip Erdoğan');
INSERT INTO head_of_state () VALUES ('Turkmenistan', 'President – Serdar Berdimuhamedow');
INSERT INTO head_of_state () VALUES ('Tuvalu', 'King – Charles III\nGovernor-General – Sir Tofiga Vaevalu Falani');
INSERT INTO head_of_state () VALUES ('Uganda', 'President – Yoweri Museveni');
INSERT INTO head_of_state () VALUES ('Ukraine', 'President – Volodymyr Zelenskyy');
INSERT INTO head_of_state () VALUES ('United Arab Emirates', 'President – Sheikh Mohamed bin Zayed Al Nahyan');
INSERT INTO head_of_state () VALUES ('United Kingdom', 'King – Charles III');
INSERT INTO head_of_state () VALUES ('United States', 'President – Joe Biden');
INSERT INTO head_of_state () VALUES ('Uruguay', 'President – Luis Lacalle Pou');
INSERT INTO head_of_state () VALUES ('Uzbekistan', 'President – Shavkat Mirziyoyev');
INSERT INTO head_of_state () VALUES ('Vanuatu', 'President – Nikenike Vurobaravu');
INSERT INTO head_of_state () VALUES ('Vatican City', 'Sovereign – Pope Francis');
INSERT INTO head_of_state () VALUES ('Venezuela', 'President – Nicolás Maduro');
INSERT INTO head_of_state () VALUES ('Vietnam', 'General Secretary of the Communist Party – Nguyễn Phú Trọng');
INSERT INTO head_of_state () VALUES ('Vietnam', 'President – Nguyễn Xuân Phúc');
INSERT INTO head_of_state () VALUES ('Yemen', 'Chairman of the Presidential Leadership Council – Rashad al-Alimi');
INSERT INTO head_of_state () VALUES ('Zambia', 'President – Hakainde Hichilema');
INSERT INTO head_of_state () VALUES ('Zimbabwe', 'President – Emmerson Mnangagwa');
