INSERT INTO head_of_state () VALUES ('Abkhazia', 'President – Aslan Bzhania', 'Prime Minister – Aleksander Ankvab');
INSERT INTO head_of_state () VALUES ('Afghanistan', 'Supreme Leader – Hibatullah Akhundzada', 'Acting Prime Minister – Hasan Akhund');
INSERT INTO head_of_state () VALUES ('Albania', 'President – Bajram Begaj', 'Prime Minister – Edi Rama');
INSERT INTO head_of_state () VALUES ('Algeria', 'President – Abdelmadjid Tebboune', 'Prime Minister – Aymen Benabderrahmane');
INSERT INTO head_of_state () VALUES ('Andorra', 'Episcopal Co-Prince – Joan Enric Vives i Sicília\nCo-Prince''s Representative – Josep Maria Mauri\nFrench Co-Prince – Emmanuel Macron\nCo-Prince''s Representative – Patrick Strzoda', 'Prime Minister – Xavier Espot Zamora');
INSERT INTO head_of_state () VALUES ('Angola', 'President – João Lourenço', 'President – João Lourenço');
INSERT INTO head_of_state () VALUES ('Antigua and Barbuda', 'King – Charles III\nGovernor-General – Sir Rodney Williams', 'Prime Minister – Gaston Browne');
INSERT INTO head_of_state () VALUES ('Argentina', 'President – Alberto Fernández', 'President – Alberto Fernández');
INSERT INTO head_of_state () VALUES ('Armenia', 'President – Vahagn Khachaturyan', 'Prime Minister – Nikol Pashinyan');
INSERT INTO head_of_state () VALUES ('Australia', 'King – Charles III\nGovernor-General – David Hurley', 'Prime Minister – Anthony Albanese');
INSERT INTO head_of_state () VALUES ('Austria', 'President – Alexander Van der Bellen', 'Chancellor – Karl Nehammer');
INSERT INTO head_of_state () VALUES ('Azerbaijan', 'President – Ilham Aliyev', 'Prime Minister – Ali Asadov');
INSERT INTO head_of_state () VALUES ('Bahamas, The', 'King – Charles III\nGovernor-General – Sir Cornelius A. Smith', 'Prime Minister – Philip Davis');
INSERT INTO head_of_state () VALUES ('Bahrain', 'King – Sheikh Hamad bin Isa Al Khalifa', 'Prime Minister – Prince Salman bin Hamad Al Khalifa');
INSERT INTO head_of_state () VALUES ('Bangladesh', 'President – Abdul Hamid', 'Prime Minister – Sheikh Hasina');
INSERT INTO head_of_state () VALUES ('Barbados', 'President – Dame Sandra Mason', 'Prime Minister – Mia Mottley');
INSERT INTO head_of_state () VALUES ('Belarus', 'President – Alexander Lukashenko', 'President – Alexander Lukashenko');
INSERT INTO head_of_state () VALUES ('Belgium', 'King – Philippe', 'Prime Minister – Alexander De Croo');
INSERT INTO head_of_state () VALUES ('Belize', 'King – Charles III\nGovernor-General – Dame Froyla Tzalam', 'Prime Minister – Johnny Briceño');
INSERT INTO head_of_state () VALUES ('Benin', 'President – Patrice Talon', 'President – Patrice Talon');
INSERT INTO head_of_state () VALUES ('Bhutan', 'King – Jigme Khesar Namgyel Wangchuck', 'Prime Minister – Lotay Tshering');
INSERT INTO head_of_state () VALUES ('Bolivia', 'President – Luis Arce', 'President – Luis Arce');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'High Representative – Christian Schmidt', 'High Representative – Christian Schmidt');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Presidency', 'Prime Minister – Zoran Tegeltija');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Željka Cvijanović (as Chairwoman)', 'Prime Minister – Zoran Tegeltija');
INSERT INTO head_of_state () VALUES ('Bosnia and Herzegovina', 'Denis Bećirović (as Member)\nŽeljko Komšić (as Member)', 'Prime Minister – Zoran Tegeltija');
INSERT INTO head_of_state () VALUES ('Botswana', 'President – Mokgweetsi Masisi', 'President – Mokgweetsi Masisi');
INSERT INTO head_of_state () VALUES ('Brazil', 'President – Jair Bolsonaro', 'President – Jair Bolsonaro');
INSERT INTO head_of_state () VALUES ('Brazil', 'President-elect – Luiz Inácio Lula da Silva', 'President-elect – Luiz Inácio Lula da Silva');
INSERT INTO head_of_state () VALUES ('Brunei', 'Sultan and Prime Minister – Hassanal Bolkiah', 'Sultan and Prime Minister – Hassanal Bolkiah');
INSERT INTO head_of_state () VALUES ('Bulgaria', 'President – Rumen Radev', 'Prime Minister – Galab Donev');
INSERT INTO head_of_state () VALUES ('Burkina Faso', 'President of the Patriotic Movement for Safeguard and Restoration – Ibrahim Traoré', 'President of the Patriotic Movement for Safeguard and Restoration – Ibrahim Traoré');
INSERT INTO head_of_state () VALUES ('Burkina Faso', 'Interim President – Ibrahim Traoré', 'Interim Prime Minister – Apollinaire Joachim Kyélem de Tambèla');
INSERT INTO head_of_state () VALUES ('Burundi', 'President – Évariste Ndayishimiye', 'Prime Minister – Gervais Ndirakobuca');
INSERT INTO head_of_state () VALUES ('Cambodia', 'King – Norodom Sihamoni', 'Prime Minister – Hun Sen');
INSERT INTO head_of_state () VALUES ('Cameroon', 'President – Paul Biya', 'Prime Minister – Joseph Ngute');
INSERT INTO head_of_state () VALUES ('Canada', 'King – Charles III\nGovernor General – Mary Simon', 'Prime Minister – Justin Trudeau');
INSERT INTO head_of_state () VALUES ('Cape Verde', 'President – José Maria Neves', 'Prime Minister – Ulisses Correia e Silva');
INSERT INTO head_of_state () VALUES ('Central African Republic', 'President – Faustin-Archange Touadéra', 'Prime Minister – Félix Moloua');
INSERT INTO head_of_state () VALUES ('Chad', 'Transitional President – Mahamat Déby', 'Prime Minister – Saleh Kebzabo');
INSERT INTO head_of_state () VALUES ('Chile', 'President – Gabriel Boric', 'President – Gabriel Boric');
INSERT INTO head_of_state () VALUES ('China', 'General Secretary of the Communist Party – Xi Jinping', 'General Secretary of the Communist Party – Xi Jinping');
INSERT INTO head_of_state () VALUES ('China', 'President – Xi Jinping', 'Premier – Li Keqiang\nPremier-designate – Li Qiang');
INSERT INTO head_of_state () VALUES ('Colombia', 'President – Gustavo Petro', 'President – Gustavo Petro');
INSERT INTO head_of_state () VALUES ('Comoros', 'President – Azali Assoumani', 'President – Azali Assoumani');
INSERT INTO head_of_state () VALUES ('Congo, Democratic Republic of the', 'President – Félix Tshisekedi', 'Prime Minister – Jean-Michel Sama Lukonde');
INSERT INTO head_of_state () VALUES ('Congo, Republic of the', 'President – Denis Sassou Nguesso', 'Prime Minister – Anatole Collinet Makosso');
INSERT INTO head_of_state () VALUES ('Cook Islands', 'King – Charles III\nKing''s Representative – Sir Tom Marsters', 'Prime Minister – Mark Brown');
INSERT INTO head_of_state () VALUES ('Costa Rica', 'President – Rodrigo Chaves Robles', 'President – Rodrigo Chaves Robles');
INSERT INTO head_of_state () VALUES ('Croatia', 'President – Zoran Milanović', 'Prime Minister – Andrej Plenković');
INSERT INTO head_of_state () VALUES ('Cuba', 'First Secretary of the Communist Party – Miguel Díaz-Canel', 'First Secretary of the Communist Party – Miguel Díaz-Canel');
INSERT INTO head_of_state () VALUES ('Cuba', 'President – Miguel Díaz-Canel', 'Prime Minister – Manuel Marrero Cruz');
INSERT INTO head_of_state () VALUES ('Cyprus', 'President – Nicos Anastasiades', 'President – Nicos Anastasiades');
INSERT INTO head_of_state () VALUES ('Czech Republic', 'President – Miloš Zeman', 'Prime Minister – Petr Fiala');
INSERT INTO head_of_state () VALUES ('Denmark', 'Queen – Margrethe II', 'Prime Minister – Mette Frederiksen');
INSERT INTO head_of_state () VALUES ('Djibouti', 'President – Ismaïl Omar Guelleh', 'Prime Minister – Abdoulkader Kamil Mohamed');
INSERT INTO head_of_state () VALUES ('Dominica', 'President – Charles Savarin', 'Prime Minister – Roosevelt Skerrit');
INSERT INTO head_of_state () VALUES ('Dominican Republic', 'President – Luis Abinader', 'President – Luis Abinader');
INSERT INTO head_of_state () VALUES ('East Timor', 'President – José Ramos-Horta', 'Prime Minister – Taur Matan Ruak');
INSERT INTO head_of_state () VALUES ('Ecuador', 'President – Guillermo Lasso', 'President – Guillermo Lasso');
INSERT INTO head_of_state () VALUES ('Egypt', 'President – Abdel Fattah el-Sisi', 'Prime Minister – Mostafa Madbouly');
INSERT INTO head_of_state () VALUES ('El Salvador', 'President – Nayib Bukele', 'President – Nayib Bukele');
INSERT INTO head_of_state () VALUES ('Equatorial Guinea', 'President – Teodoro Obiang Nguema Mbasogo', 'Prime Minister – Francisco Pascual Obama Asue');
INSERT INTO head_of_state () VALUES ('Eritrea', 'Chairman of the People''s Front for Democracy and Justice – Isaias Afwerki', 'Chairman of the People''s Front for Democracy and Justice – Isaias Afwerki');
INSERT INTO head_of_state () VALUES ('Eritrea', 'President – Isaias Afwerki', 'President – Isaias Afwerki');
INSERT INTO head_of_state () VALUES ('Estonia', 'President – Alar Karis', 'Prime Minister – Kaja Kallas');
INSERT INTO head_of_state () VALUES ('Eswatini', 'King – Mswati III', 'Acting Prime Minister – Cleopas Dlamini');
INSERT INTO head_of_state () VALUES ('Ethiopia', 'President – Sahle-Work Zewde', 'Prime Minister – Abiy Ahmed');
INSERT INTO head_of_state () VALUES ('Federated States of Micronesia', 'President – David W. Panuelo', 'President – David W. Panuelo');
INSERT INTO head_of_state () VALUES ('Fiji', 'President – Ratu Wiliame Katonivere', 'Prime Minister – Frank Bainimarama');
INSERT INTO head_of_state () VALUES ('Finland', 'President – Sauli Niinistö', 'Prime Minister – Sanna Marin');
INSERT INTO head_of_state () VALUES ('France', 'President – Emmanuel Macron', 'Prime Minister – Élisabeth Borne');
INSERT INTO head_of_state () VALUES ('Gabon', 'President – Ali Bongo Ondimba', 'Prime Minister – Rose Christiane Raponda');
INSERT INTO head_of_state () VALUES ('Gambia, The', 'President – Adama Barrow', 'President – Adama Barrow');
INSERT INTO head_of_state () VALUES ('Georgia', 'President – Salome Zourabichvili', 'Prime Minister – Irakli Garibashvili');
INSERT INTO head_of_state () VALUES ('Germany', 'President – Frank-Walter Steinmeier', 'Chancellor – Olaf Scholz');
INSERT INTO head_of_state () VALUES ('Ghana', 'President – Nana Akufo-Addo', 'President – Nana Akufo-Addo');
INSERT INTO head_of_state () VALUES ('Greece', 'President – Katerina Sakellaropoulou', 'Prime Minister – Kyriakos Mitsotakis');
INSERT INTO head_of_state () VALUES ('Grenada', 'King – Charles III\nGovernor-General – Dame Cécile La Grenade', 'Prime Minister – Dickon Mitchell');
INSERT INTO head_of_state () VALUES ('Guatemala', 'President – Alejandro Giammattei', 'President – Alejandro Giammattei');
INSERT INTO head_of_state () VALUES ('Guinea', 'Chairman of the National Committee of Reconciliation and Development – Mamady Doumbouya', 'Chairman of the National Committee of Reconciliation and Development – Mamady Doumbouya');
INSERT INTO head_of_state () VALUES ('Guinea', 'Interim President – Mamady Doumbouya', 'Interim Prime Minister – Bernard Gomou');
INSERT INTO head_of_state () VALUES ('Guinea-Bissau', 'President – Umaro Sissoco Embaló', 'Prime Minister – Nuno Gomes Nabiam');
INSERT INTO head_of_state () VALUES ('Guyana', 'President – Irfaan Ali', 'Prime Minister – Mark Phillips');
INSERT INTO head_of_state () VALUES ('Haiti', 'Interim President – Ariel Henry', 'Prime Minister – Ariel Henry');
INSERT INTO head_of_state () VALUES ('Honduras', 'President – Xiomara Castro', 'President – Xiomara Castro');
INSERT INTO head_of_state () VALUES ('Hungary', 'President – Katalin Novák', 'Prime Minister – Viktor Orbán');
INSERT INTO head_of_state () VALUES ('Iceland', 'President – Guðni Th. Jóhannesson', 'Prime Minister – Katrín Jakobsdóttir');
INSERT INTO head_of_state () VALUES ('India', 'President – Droupadi Murmu', 'Prime Minister – Narendra Modi');
INSERT INTO head_of_state () VALUES ('Indonesia', 'President – Joko Widodo', 'President – Joko Widodo');
INSERT INTO head_of_state () VALUES ('Iran', 'Supreme Leader – Ali Khamenei', 'President – Ebrahim Raisi');
INSERT INTO head_of_state () VALUES ('Iraq', 'President – Abdul Latif Rashid', 'Prime Minister – Mohammed Shia'' Al Sudani');
INSERT INTO head_of_state () VALUES ('Ireland', 'President – Michael D. Higgins', 'Taoiseach-designate – Leo Varadkar');
INSERT INTO head_of_state () VALUES ('Ireland', 'President – Michael D. Higgins', 'Taoiseach – Micheál Martin');
INSERT INTO head_of_state () VALUES ('Israel', 'President – Isaac Herzog', 'Prime Minister – Yair Lapid');
INSERT INTO head_of_state () VALUES ('Israel', 'President – Isaac Herzog', 'Prime minister-designate – Benjamin Netanyahu');
INSERT INTO head_of_state () VALUES ('Italy', 'President – Sergio Mattarella', 'Prime Minister – Giorgia Meloni');
INSERT INTO head_of_state () VALUES ('Ivory Coast', 'President – Alassane Ouattara', 'Prime Minister – Patrick Achi');
INSERT INTO head_of_state () VALUES ('Jamaica', 'King – Charles III\nGovernor-General – Sir Patrick Allen', 'Prime Minister – Andrew Holness');
INSERT INTO head_of_state () VALUES ('Japan', 'Emperor – Naruhito', 'Prime Minister – Fumio Kishida');
INSERT INTO head_of_state () VALUES ('Jordan', 'King – Abdullah II', 'Prime Minister – Bisher Al-Khasawneh');
INSERT INTO head_of_state () VALUES ('Kazakhstan', 'President – Qasym-Zhomart Toqaev', 'Prime Minister – Älihan Smaiylov');
INSERT INTO head_of_state () VALUES ('Kenya', 'President – William Ruto', 'President – William Ruto');
INSERT INTO head_of_state () VALUES ('Kiribati', 'President – Taneti Maamau', 'President – Taneti Maamau');
INSERT INTO head_of_state () VALUES ('Kosovo', 'President – Vjosa Osmani', 'Prime Minister – Albin Kurti');
INSERT INTO head_of_state () VALUES ('Kuwait', 'Emir – Sheikh Nawaf Al-Ahmad Al-Jaber Al-Sabah', 'Prime Minister – Sheikh Ahmad Nawaf Al-Ahmad Al-Sabah');
INSERT INTO head_of_state () VALUES ('Kyrgyzstan', 'President – Sadyr Japarov', 'Chairman of the Cabinet of Ministers – Akylbek Japarov');
INSERT INTO head_of_state () VALUES ('Laos', 'General Secretary of the People''s Revolutionary Party – Thongloun Sisoulith', 'General Secretary of the People''s Revolutionary Party – Thongloun Sisoulith');
INSERT INTO head_of_state () VALUES ('Laos', 'President – Thongloun Sisoulith', 'Prime Minister – Phankham Viphavanh');
INSERT INTO head_of_state () VALUES ('Latvia', 'President – Egils Levits', 'Prime Minister – Krišjānis Kariņš');
INSERT INTO head_of_state () VALUES ('Lebanon', 'Acting President – Najib Mikati', 'Prime Minister – Najib Mikati');
INSERT INTO head_of_state () VALUES ('Lesotho', 'King – Letsie III', 'Prime Minister – Sam Matekane');
INSERT INTO head_of_state () VALUES ('Liberia', 'President – George Weah', 'President – George Weah');
INSERT INTO head_of_state () VALUES ('Libya', 'Chairman of the Presidential Council – Mohamed al-Menfi', 'Prime Minister – Abdul Hamid Dbeibeh');
INSERT INTO head_of_state () VALUES ('Liechtenstein', 'Regent – Hereditary Prince Alois', 'Prime Minister – Daniel Risch');
INSERT INTO head_of_state () VALUES ('Liechtenstein', 'Prince Regnant – Hans-Adam II', 'Prime Minister – Daniel Risch');
INSERT INTO head_of_state () VALUES ('Lithuania', 'President – Gitanas Nausėda', 'Prime Minister – Ingrida Šimonytė');
INSERT INTO head_of_state () VALUES ('Luxembourg', 'Grand Duke – Henri', 'Prime Minister – Xavier Bettel');
INSERT INTO head_of_state () VALUES ('Madagascar', 'President – Andry Rajoelina', 'Prime Minister – Christian Ntsay');
INSERT INTO head_of_state () VALUES ('Malawi', 'President – Lazarus Chakwera', 'President – Lazarus Chakwera');
INSERT INTO head_of_state () VALUES ('Malaysia', 'Yang di-Pertuan Agong – Abdullah Sultan Ahmad Shah', 'Prime Minister – Anwar Ibrahim');
INSERT INTO head_of_state () VALUES ('Maldives', 'President – Ibrahim Mohamed Solih', 'President – Ibrahim Mohamed Solih');
INSERT INTO head_of_state () VALUES ('Mali', 'Interim President – Assimi Goïta', 'Interim Prime Minister – Abdoulaye Maïga');
INSERT INTO head_of_state () VALUES ('Malta', 'President – George Vella', 'Prime Minister – Robert Abela');
INSERT INTO head_of_state () VALUES ('Marshall Islands', 'President – David Kabua', 'President – David Kabua');
INSERT INTO head_of_state () VALUES ('Mauritania', 'President – Mohamed Ould Ghazouani', 'Prime Minister – Mohamed Ould Bilal');
INSERT INTO head_of_state () VALUES ('Mauritius', 'President – Prithvirajsing Roopun', 'Prime Minister – Pravind Jugnauth');
INSERT INTO head_of_state () VALUES ('Mexico', 'President – Andrés Manuel López Obrador', 'President – Andrés Manuel López Obrador');
INSERT INTO head_of_state () VALUES ('Moldova', 'President – Maia Sandu', 'Prime Minister – Natalia Gavrilița');
INSERT INTO head_of_state () VALUES ('Monaco', 'Sovereign Prince – Albert II', 'Minister of State – Pierre Dartout');
INSERT INTO head_of_state () VALUES ('Mongolia', 'President – Ukhnaagiin Khürelsükh', 'Prime Minister – Luvsannamsrain Oyun-Erdene');
INSERT INTO head_of_state () VALUES ('Montenegro', 'President – Milo Đukanović', 'Prime Minister – Dritan Abazović');
INSERT INTO head_of_state () VALUES ('Morocco', 'King – Mohammed VI', 'Prime Minister – Aziz Akhannouch');
INSERT INTO head_of_state () VALUES ('Mozambique', 'President – Filipe Nyusi', 'Prime Minister – Adriano Maleiane');
INSERT INTO head_of_state () VALUES ('Myanmar', 'Chairman of the State Administration Council – Min Aung Hlaing', 'Chairman of the State Administration Council – Min Aung Hlaing');
INSERT INTO head_of_state () VALUES ('Myanmar', 'Acting President – Myint Swe', 'Prime Minister – Min Aung Hlaing');
INSERT INTO head_of_state () VALUES ('Namibia', 'President – Hage Geingob', 'Prime Minister – Saara Kuugongelwa');
INSERT INTO head_of_state () VALUES ('Nauru', 'President – Russ Kun', 'President – Russ Kun');
INSERT INTO head_of_state () VALUES ('Nepal', 'President – Bidya Devi Bhandari', 'Prime Minister – Sher Bahadur Deuba');
INSERT INTO head_of_state () VALUES ('Netherlands', 'King – Willem-Alexander', 'Prime Minister – Mark Rutte');
INSERT INTO head_of_state () VALUES ('New Zealand', 'King – Charles III\nGovernor-General – Dame Cindy Kiro', 'Prime Minister – Jacinda Ardern');
INSERT INTO head_of_state () VALUES ('Nicaragua', 'President – Daniel Ortega', 'President – Daniel Ortega');
INSERT INTO head_of_state () VALUES ('Niger', 'President – Mohamed Bazoum', 'Prime Minister – Ouhoumoudou Mahamadou');
INSERT INTO head_of_state () VALUES ('Nigeria', 'President – Muhammadu Buhari', 'President – Muhammadu Buhari');
INSERT INTO head_of_state () VALUES ('Niue', 'King – Charles III\nKing''s Representative – Dame Cindy Kiro', 'Premier – Dalton Tagelagi');
INSERT INTO head_of_state () VALUES ('North Korea', 'General Secretary of the Workers'' Party of Korea – Kim Jong-un', 'General Secretary of the Workers'' Party of Korea – Kim Jong-un');
INSERT INTO head_of_state () VALUES ('North Korea', 'President of the State Affairs Commission – Kim Jong-un', 'Premier – Kim Tok-hun');
INSERT INTO head_of_state () VALUES ('North Macedonia', 'President – Stevo Pendarovski', 'Prime Minister – Dimitar Kovačevski');
INSERT INTO head_of_state () VALUES ('Northern Cyprus', 'President – Ersin Tatar', 'Prime Minister – Ünal Üstel');
INSERT INTO head_of_state () VALUES ('Norway', 'King – Harald V', 'Prime Minister – Jonas Gahr Støre');
INSERT INTO head_of_state () VALUES ('Oman', 'Sultan and Prime Minister – Haitham bin Tariq', 'Sultan and Prime Minister – Haitham bin Tariq');
INSERT INTO head_of_state () VALUES ('Pakistan', 'President – Arif Alvi', 'Prime Minister – Shehbaz Sharif');
INSERT INTO head_of_state () VALUES ('Palau', 'President – Surangel Whipps Jr.', 'President – Surangel Whipps Jr.');
INSERT INTO head_of_state () VALUES ('Palestine', 'President – Mahmoud Abbas', 'Prime Minister – Mohammad Shtayyeh');
INSERT INTO head_of_state () VALUES ('Panama', 'President – Laurentino Cortizo', 'President – Laurentino Cortizo');
INSERT INTO head_of_state () VALUES ('Papua New Guinea', 'King – Charles III\nGovernor-General – Sir Bob Dadae', 'Prime Minister – James Marape');
INSERT INTO head_of_state () VALUES ('Paraguay', 'President – Mario Abdo Benítez', 'President – Mario Abdo Benítez');
INSERT INTO head_of_state () VALUES ('Peru', 'President – Dina Boluarte', 'President – Dina Boluarte');
INSERT INTO head_of_state () VALUES ('Philippines', 'President – Bongbong Marcos', 'President – Bongbong Marcos');
INSERT INTO head_of_state () VALUES ('Poland', 'President – Andrzej Duda', 'Prime Minister – Mateusz Morawiecki');
INSERT INTO head_of_state () VALUES ('Portugal', 'President – Marcelo Rebelo de Sousa', 'Prime Minister – António Costa');
INSERT INTO head_of_state () VALUES ('Qatar', 'Emir – Sheikh Tamim bin Hamad Al Thani', 'Prime Minister – Sheikh Khalid bin Khalifa bin Abdul Aziz Al Thani');
INSERT INTO head_of_state () VALUES ('Republic of China (Taiwan)', 'President – Tsai Ing-wen', 'Premier – Su Tseng-chang');
INSERT INTO head_of_state () VALUES ('Romania', 'President – Klaus Iohannis', 'Prime Minister – Nicolae Ciucă');
INSERT INTO head_of_state () VALUES ('Russia', 'President – Vladimir Putin', 'Prime Minister – Mikhail Mishustin');
INSERT INTO head_of_state () VALUES ('Rwanda', 'President – Paul Kagame', 'Prime Minister – Édouard Ngirente');
INSERT INTO head_of_state () VALUES ('Sahrawi Republic', 'President – Brahim Ghali', 'Prime Minister – Bouchraya Hammoudi Bayoun');
INSERT INTO head_of_state () VALUES ('Sahrawi Republic', 'General Secretary of the Polisario Front – Brahim Ghali', 'General Secretary of the Polisario Front – Brahim Ghali');
INSERT INTO head_of_state () VALUES ('Saint Kitts and Nevis', 'King – Charles III\nGovernor-General – Sir Tapley Seaton', 'Prime Minister – Terrance Drew');
INSERT INTO head_of_state () VALUES ('Saint Lucia', 'King – Charles III\nActing Governor-General – Errol Charles', 'Prime Minister – Philip J. Pierre');
INSERT INTO head_of_state () VALUES ('Saint Vincent and the Grenadines', 'King – Charles III\nGovernor-General – Dame Susan Dougan', 'Prime Minister – Ralph Gonsalves');
INSERT INTO head_of_state () VALUES ('Samoa', 'O le Ao o le Malo – Afioga Tuimalealiʻifano Vaʻaletoʻa Sualauvi II', 'Prime Minister – Fiamē Naomi Mataʻafa');
INSERT INTO head_of_state () VALUES ('San Marino', 'Captain Regent – Maria Luisa Berti', 'Secretary for Foreign and Political Affairs – Luca Beccari');
INSERT INTO head_of_state () VALUES ('San Marino', 'Captain Regent – Manuel Ciavatta', 'Secretary for Foreign and Political Affairs – Luca Beccari');
INSERT INTO head_of_state () VALUES ('Saudi Arabia', 'King – Salman', 'Prime Minister – Mohammed bin Salman');
INSERT INTO head_of_state () VALUES ('Senegal', 'President – Macky Sall', 'Prime Minister – Amadou Ba');
INSERT INTO head_of_state () VALUES ('Serbia', 'President – Aleksandar Vučić', 'Prime Minister – Ana Brnabić');
INSERT INTO head_of_state () VALUES ('Seychelles', 'President – Wavel Ramkalawan', 'President – Wavel Ramkalawan');
INSERT INTO head_of_state () VALUES ('Sierra Leone', 'President – Julius Maada Bio', 'Chief Minister – Jacob Jusu Saffa');
INSERT INTO head_of_state () VALUES ('Singapore', 'President – Halimah Yacob', 'Prime Minister – Lee Hsien Loong');
INSERT INTO head_of_state () VALUES ('Slovakia', 'President – Zuzana Čaputová', 'Prime Minister – Eduard Heger');
INSERT INTO head_of_state () VALUES ('Slovenia', 'President – Borut Pahor\nPresident-elect – Nataša Pirc Musar', 'Prime Minister – Robert Golob');
INSERT INTO head_of_state () VALUES ('Solomon Islands', 'King – Charles III\nGovernor-General – Sir David Vunagi', 'Prime Minister – Manasseh Sogavare');
INSERT INTO head_of_state () VALUES ('Somalia', 'President – Hassan Sheikh Mohamud', 'Prime Minister – Hamza Abdi Barre');
INSERT INTO head_of_state () VALUES ('South Africa', 'President – Cyril Ramaphosa', 'President – Cyril Ramaphosa');
INSERT INTO head_of_state () VALUES ('South Korea', 'President – Yoon Suk-yeol', 'President – Yoon Suk-yeol');
INSERT INTO head_of_state () VALUES ('South Ossetia', 'President – Alan Gagloyev', 'Prime Minister – Konstantin Dzhussoyev');
INSERT INTO head_of_state () VALUES ('South Sudan', 'President – Salva Kiir Mayardit', 'President – Salva Kiir Mayardit');
INSERT INTO head_of_state () VALUES ('Spain', 'King – Felipe VI', 'Prime Minister – Pedro Sánchez');
INSERT INTO head_of_state () VALUES ('Sri Lanka', 'President – Ranil Wickremesinghe', 'President – Ranil Wickremesinghe');
INSERT INTO head_of_state () VALUES ('Sudan', 'Chairman of the Transitional Sovereignty Council – Abdel Fattah al-Burhan', 'Acting Prime Minister – Osman Hussein');
INSERT INTO head_of_state () VALUES ('Suriname', 'President – Chan Santokhi', 'President – Chan Santokhi');
INSERT INTO head_of_state () VALUES ('Sweden', 'King – Carl XVI Gustaf', 'Prime Minister – Ulf Kristersson');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Members: \nIgnazio Cassis (President)\nAlain Berset (Vice President)\nUeli Maurer\nSimonetta Sommaruga\nGuy Parmelin\nKarin Keller-Sutter\nViola Amherd', 'Members: \nIgnazio Cassis (President)\nAlain Berset (Vice President)\nUeli Maurer\nSimonetta Sommaruga\nGuy Parmelin\nKarin Keller-Sutter\nViola Amherd');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Federal Council', 'Federal Council');
INSERT INTO head_of_state () VALUES ('Switzerland', 'Members-elect of the Federal Council: \nAlbert Rösti\nÉlisabeth Baume-Schneider', 'Members-elect of the Federal Council: \nAlbert Rösti\nÉlisabeth Baume-Schneider');
INSERT INTO head_of_state () VALUES ('Syria', 'President – Bashar al-Assad', 'Prime Minister – Hussein Arnous');
INSERT INTO head_of_state () VALUES ('São Tomé and Príncipe', 'President – Carlos Vila Nova', 'Prime Minister – Patrice Trovoada');
INSERT INTO head_of_state () VALUES ('Tajikistan', 'President – Emomali Rahmon', 'Prime Minister – Kokhir Rasulzoda');
INSERT INTO head_of_state () VALUES ('Tanzania', 'President – Samia Suluhu Hassan', 'Prime Minister – Kassim Majaliwa');
INSERT INTO head_of_state () VALUES ('Thailand', 'King – Maha Vajiralongkorn', 'Prime Minister – Prayut Chan-o-cha');
INSERT INTO head_of_state () VALUES ('Togo', 'President – Faure Gnassingbé', 'Prime Minister – Victoire Tomegah Dogbé');
INSERT INTO head_of_state () VALUES ('Tonga', 'King – Tupou VI', 'Prime Minister – Siaosi Sovaleni');
INSERT INTO head_of_state () VALUES ('Trinidad and Tobago', 'President – Paula-Mae Weekes', 'Prime Minister – Keith Rowley');
INSERT INTO head_of_state () VALUES ('Tunisia', 'President – Kaïs Saïed', 'Prime Minister – Najla Bouden');
INSERT INTO head_of_state () VALUES ('Turkey', 'President – Recep Tayyip Erdoğan', 'President – Recep Tayyip Erdoğan');
INSERT INTO head_of_state () VALUES ('Turkmenistan', 'President – Serdar Berdimuhamedow', 'President – Serdar Berdimuhamedow');
INSERT INTO head_of_state () VALUES ('Tuvalu', 'King – Charles III\nGovernor-General – Sir Tofiga Vaevalu Falani', 'Prime Minister – Kausea Natano');
INSERT INTO head_of_state () VALUES ('Uganda', 'President – Yoweri Museveni', 'Prime Minister – Robinah Nabbanja');
INSERT INTO head_of_state () VALUES ('Ukraine', 'President – Volodymyr Zelenskyy', 'Prime Minister – Denys Shmyhal');
INSERT INTO head_of_state () VALUES ('United Arab Emirates', 'President – Sheikh Mohamed bin Zayed Al Nahyan', 'Prime Minister – Sheikh Mohammed bin Rashid Al Maktoum');
INSERT INTO head_of_state () VALUES ('United Kingdom', 'King – Charles III', 'Prime Minister – Rishi Sunak');
INSERT INTO head_of_state () VALUES ('United States', 'President – Joe Biden', 'President – Joe Biden');
INSERT INTO head_of_state () VALUES ('Uruguay', 'President – Luis Lacalle Pou', 'President – Luis Lacalle Pou');
INSERT INTO head_of_state () VALUES ('Uzbekistan', 'President – Shavkat Mirziyoyev', 'Prime Minister – Abdulla Aripov');
INSERT INTO head_of_state () VALUES ('Vanuatu', 'President – Nikenike Vurobaravu', 'Prime Minister – Ishmael Kalsakau');
INSERT INTO head_of_state () VALUES ('Vatican City', 'Sovereign – Pope Francis', 'President of the Governorate – Cardinal Fernando Vérgez Alzaga');
INSERT INTO head_of_state () VALUES ('Venezuela', 'President – Nicolás Maduro', 'President – Nicolás Maduro');
INSERT INTO head_of_state () VALUES ('Vietnam', 'General Secretary of the Communist Party – Nguyễn Phú Trọng', 'General Secretary of the Communist Party – Nguyễn Phú Trọng');
INSERT INTO head_of_state () VALUES ('Vietnam', 'President – Nguyễn Xuân Phúc', 'Prime Minister – Phạm Minh Chính');
INSERT INTO head_of_state () VALUES ('Yemen', 'Chairman of the Presidential Leadership Council – Rashad al-Alimi', 'Prime Minister – Maeen Abdulmalik Saeed');
INSERT INTO head_of_state () VALUES ('Zambia', 'President – Hakainde Hichilema', 'President – Hakainde Hichilema');
INSERT INTO head_of_state () VALUES ('Zimbabwe', 'President – Emmerson Mnangagwa', 'President – Emmerson Mnangagwa');
