INSERT INTO Idioma () VALUES ('Abkhazia', 'Abkhaz\nRussian', NULL, 'Georgian', 'Abkhaz', NULL);
INSERT INTO Idioma () VALUES ('Afghanistan', 'Persian (Dari)\nPashto', 'Uzbek\nTurkmen\nPashayi\nNuristani\nBalochi\nPamiri', NULL, 'Persian (Dari)\nPashto', 'Persian (Dari)');
INSERT INTO Idioma () VALUES ('Albania', 'Albanian', NULL, 'Greek\nMacedonian\nAromanian', NULL, 'Italian');
INSERT INTO Idioma () VALUES ('Algeria', 'Arabic\nTamazight', NULL, NULL, 'Arabic\nTamazight', 'French');
INSERT INTO Idioma () VALUES ('Andorra', 'Catalan', NULL, 'Spanish\nFrench\nPortuguese', NULL, NULL);
INSERT INTO Idioma () VALUES ('Angola', 'Portuguese', NULL, NULL, 'Kimbundu\nUmbundu\nKikongo\nChokwe\nKwanyama\nGanguela[citation needed]', 'Angolan Portuguese');
INSERT INTO Idioma () VALUES ('Antigua and Barbuda', 'English', NULL, NULL, NULL, 'Antiguan and Barbudan Creole');
INSERT INTO Idioma () VALUES ('Argentina', 'None (Spanish has de facto status)', 'Spanish (in Corrientes and Chaco)\nGuaraní (in Corrientes)\nKom (in Chaco)\nMoquoit (in Chaco)\nWichi (in Chaco)', NULL, NULL, 'Argentine Spanish');
INSERT INTO Idioma () VALUES ('Armenia', 'Armenian', NULL, NULL, 'Armenian (state language)', NULL);
INSERT INTO Idioma () VALUES ('Artsakh', 'Armenian\nRussian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Australia', 'None (English has de facto status)', 'Norfuk language (on Norfolk island)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Austria', 'German', 'Burgenland Croatian (parts of Burgenland)\nHungarian (parts of Burgenland)\nSlovene (parts of Carinthia)', 'Slovene\nCzech\nHungarian\nSlovak\nRomani\nSerbian', 'German (state language)', NULL);
INSERT INTO Idioma () VALUES ('Azerbaijan', 'Azerbaijani', NULL, NULL, 'Azerbaijani (state language)', NULL);
INSERT INTO Idioma () VALUES ('Bahamas', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Bahrain', 'Arabic', NULL, 'English', NULL, NULL);
INSERT INTO Idioma () VALUES ('Bangladesh', 'Bengali', NULL, NULL, 'Bengali', 'English');
INSERT INTO Idioma () VALUES ('Barbados', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Belarus', 'Belarusian\nRussian', NULL, NULL, 'Belarusian', NULL);
INSERT INTO Idioma () VALUES ('Belgium', 'Dutch\nFrench\nGerman', 'Dutch (Flanders, Brussels)\nFrench (Brussels, Wallonia)\nGerman (German-speaking community)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Belize', 'English', 'Spanish (border with Mexico and Guatemala)', NULL, NULL, 'Kriol (lingua franca)');
INSERT INTO Idioma () VALUES ('Benin', 'French', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Bhutan', 'Dzongkha', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Bolivia', 'Castilian (Spanish)\nAymara\nAraona\nBaure\nBésiro (Chiquitano)\nCanichana\nCavineño\nCayubaba\nChácobo\nChimán\nEse Ejja\nGuaraní\nGuarasu''we\nGuarayu\nItonama\nLeco\nMachajuyai-Kallawaya\nMachineri\nMaropa\nMojeño-Ignaciano\nMojeño-Trinitario\nMoré\nMosetén\nMovima\nPacawara\nPuquina\nQuechua\nSirionó\nTacana\nTapieté\nToromona\nUru-Chipaya\nWeenhayek\nYaminawa\nYuki\nYuracaré\nZamuco', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Bosnia and Herzegovina', 'None (Bosnian, Croatian and Serbian all have de facto status)', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Botswana', 'English', NULL, NULL, 'Tswana', 'Other Bantu languages\nSeveral Khoisan languages');
INSERT INTO Idioma () VALUES ('Brazil', 'Portuguese', 'German (in Pomerode)\nEast Pomeranian (in Pancas, Santa Maria de Jetibá, Domingos Martins, Itarana, Laranja da Terra, Vila Pavão and Canguçu)\nRiograndenser Hunsrückisch (in Antônio Carlos, Santa Catarina, and in Santa Maria do Herval, Rio Grande do Sul)\nTalian (in Bento Gonçalves, Caxias do Sul, Flores da Cunha Nova Roma do Sul and Serafina Corréa)\nNheengatu, Baniwa, Tucano (in São Gabriel de Cachoeira, Amazonas)\nGuaraní (in Tacuru, Mato Grosso do Sul)', NULL, 'Portuguese', NULL);
INSERT INTO Idioma () VALUES ('Brunei', 'Malay\nEnglish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Bulgaria', 'Bulgarian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Burkina Faso', 'French', NULL, NULL, 'Fula\nJula\nMore', NULL);
INSERT INTO Idioma () VALUES ('Burundi', 'French\nKirundi\nEnglish', NULL, NULL, 'Kirundi', 'Swahili');
INSERT INTO Idioma () VALUES ('Cambodia', 'Khmer', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Cameroon', 'English\nFrench', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Canada', 'English (Federal)\nFrench (Federal)', 'Chipewyan (Northwest Territories)\nCree (Northwest Territories)\nGwich''in (Northwest Territories)\nInuinnaqtun (Northwest Territories and Nunavut)\nInuktitut (Northwest Territories and Nunavut)\nInuvialuktun (Northwest Territories)\nNorth Slavey (Northwest Territories)\nSouth Slavey (Northwest Territories)\nTłı̨chǫ (Northwest Territories)', 'Chipewyan\nCree\nGwich''in\nInuinnaqtun\nInuktitut\nInuvialuktun\nNorth Slavey\nSouth Slavey\nTłı̨chǫ', NULL, NULL);
INSERT INTO Idioma () VALUES ('Cape Verde', 'Portuguese', NULL, NULL, 'Cape Verdean Creole', NULL);
INSERT INTO Idioma () VALUES ('Central African Republic', 'French\nSango', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Chad', 'Arabic\nFrench', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Chile', 'Chilean Spanish', '(Languages of ethnic groups are official in their territories)', NULL, 'Chilean Spanish', NULL);
INSERT INTO Idioma () VALUES ('China', 'Mandarin Chinese', 'English (Hong Kong)\nPortuguese (Macau)', 'Mongolian\nUyghur\nTibetan\nZhuang\nKazakh\nKorean', NULL, 'Other Sinitic languages');
INSERT INTO Idioma () VALUES ('Christmas Island', 'English, Mandarin Chinese, Malay', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Cocos (Keeling) Islands', 'English, Cocos Malay', NULL, NULL, NULL, 'Malay');
INSERT INTO Idioma () VALUES ('Colombia', 'Spanish', '(Languages of ethnic groups are official in their territories)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Comoros', 'Arabic\nComorian\nFrench', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Democratic Republic of the Congo', 'French', NULL, 'Lingala\nKikongo', 'Swahili\nTshiluba', NULL);
INSERT INTO Idioma () VALUES ('Republic of the Congo', 'French', NULL, 'Lingala\nMunukutuba', NULL, NULL);
INSERT INTO Idioma () VALUES ('Cook Islands', 'English, Cook Islands Māori', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Costa Rica', 'Spanish', NULL, 'Indigenous languages\nLimonese Creole', NULL, NULL);
INSERT INTO Idioma () VALUES ('Croatia', 'Croatian', 'Serbian\nHungarian\nCzech\nSlovak\nPannonian Rusyn\nIstro-Romanian (protected[clarification needed])', NULL, 'Italian (Istria County)\nRomani (non-territorial)\nSlovene (non-territorial)', NULL);
INSERT INTO Idioma () VALUES ('Cuba', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Cyprus', 'Greek\nTurkish', NULL, NULL, 'Armenian\nCypriot Arabic', 'English');
INSERT INTO Idioma () VALUES ('Czech Republic', 'Czech\nSlovak', NULL, 'Belarusian\nBulgarian\nCroatian\nGerman\nGreek\nHungarian\nPolish\nRomani\nRussian\nRusyn\nSerbian\nUkrainian\nVietnamese', 'Czech', NULL);
INSERT INTO Idioma () VALUES ('Denmark', 'Danish', 'Faroese (in the Faroe Islands)\nKalaallisut (in Greenland)', 'German (in Southern Jutland)', NULL, NULL);
INSERT INTO Idioma () VALUES ('Djibouti', 'Arabic\nFrench', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Dominica', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Dominican Republic', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('East Timor', 'Portuguese\nTetum', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Ecuador', 'Spanish\nQuechua (official language of intercultural relation)', NULL, 'Kichwa (official minority language)\nShuar (official minority language)', NULL, NULL);
INSERT INTO Idioma () VALUES ('Egypt', 'Arabic', NULL, 'Coptic', NULL, 'Egyptian Arabic');
INSERT INTO Idioma () VALUES ('El Salvador', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Equatorial Guinea', 'French\nPortuguese\nSpanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Eritrea', 'Tigrinya', NULL, NULL, NULL, 'Arabic\nItalian');
INSERT INTO Idioma () VALUES ('Estonia', 'Estonian', NULL, NULL, NULL, 'Russian');
INSERT INTO Idioma () VALUES ('Eswatini', 'English\nSwazi', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Ethiopia', 'Afar\nAmharic\nOromo\nSomali\nTigrinya', NULL, NULL, 'Afar\nAmharic\nBenshangul\nGumuz\nHarari\nKunama\nOromo\nSidamo\nSomali\nTigrinya', NULL);
INSERT INTO Idioma () VALUES ('Fiji', 'English\nFijian\nFiji Hindi', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Finland', 'Finnish\nSwedish', NULL, 'Sami (in Enontekiö, Inari, Sodankylä, Utsjoki)', 'Finnish\nSwedish', NULL);
INSERT INTO Idioma () VALUES ('France', 'French', NULL, 'Corsican language\nBasque language\nBreton language', NULL, 'Occitan language');
INSERT INTO Idioma () VALUES ('Gabon', 'French', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Gambia', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Georgia', 'Georgian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Germany', 'German', 'Danish (in Schleswig-Holstein)\nLower Sorbian (in Brandenburg)\nNorth Frisian (in Schleswig-Holstein)\nSaterland Frisian (in Lower Saxony)\nUpper Sorbian (in Saxony)\nGerman Sign Language\nLow German', 'Danish\nLower Sorbian\nNorth Frisian\nRomani\nUpper Sorbian', NULL, NULL);
INSERT INTO Idioma () VALUES ('Ghana', 'English', 'Fante\nAsante Twi\nAkuapem Twi\nAdangme (in Greater Accra)\nDagaare (in the Upper West Region)\nDagbani (in the Northern Region)\nEwe (in the Volta Region)\nGa (in the Greater Accra)\nGonja (in the Northern Region)\nKasem (in the Upper East Region)\nNzema (in the Western Region)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Greece', 'Greek', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Grenada', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Guatemala', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Guinea', 'French', NULL, NULL, NULL, 'Fula\nManinka\nSusu');
INSERT INTO Idioma () VALUES ('Guinea-Bissau', 'Portuguese', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Guyana', 'English', NULL, NULL, NULL, 'Guyanese Creole');
INSERT INTO Idioma () VALUES ('Haiti', 'French\nHaitian Creole', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Honduras', 'Spanish', 'Garifuna (on the Caribbean Coast)\nEnglish (in the Bay Islands)\nMiskito (in Eastern Honduras)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Hungary', 'Hungarian', NULL, 'Croatian\nGerman\nRomanian\nSerbian\nSlovak\nSlovene', NULL, NULL);
INSERT INTO Idioma () VALUES ('Iceland', 'Icelandic\nIcelandic Sign Language[citation needed]', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('India', 'Hindi\nEnglish', '22 official languages - Assamese, Bengali, Bodo, Dogri, Gujarati, Hindi, Kannada, Kashmiri, Konkani, Maithili, Malayalam, Meitei (Manipuri), Marathi, Nepali, Odia (Oriya), Punjabi, Sanskrit, Santali, Sindhi, Tamil, Telugu, and Urdu.', 'see Languages of India', NULL, 'see List of languages by number of native speakers in India');
INSERT INTO Idioma () VALUES ('Indonesia', 'Indonesian', 'Malay\nJavanese', NULL, 'Indonesian\nMalay', 'Malay\nJavanese\nIndonesian\nSundanese\nMadurese\nMinangkabau\nsee 700 More Languages in Indonesia');
INSERT INTO Idioma () VALUES ('Iran', 'Persian', NULL, NULL, 'Persian', 'Azerbaijani\nKurdish\nLuri\nGilaki\nMazanderani\nBalochi\nArabic\nQashqai\nTati\nTurkmeni');
INSERT INTO Idioma () VALUES ('Iraq', 'Arabic\nKurdish', 'Armenian recognized\nAssyrian Neo-Aramaic (in Assyrian areas)\nIraqi Turkmen (in Turkmen areas)\nKurdish[citation needed]', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Ireland', 'Irish\nEnglish', NULL, NULL, 'Irish', NULL);
INSERT INTO Idioma () VALUES ('Israel', 'Hebrew', 'Arabic', 'English', NULL, 'Russian\nEnglish');
INSERT INTO Idioma () VALUES ('Italy', 'Italian', 'French (in Aosta Valley)\nGerman (in South Tyrol)\nLadin (in South Tyrol)\nSlovene (in Province of Trieste, Province of Gorizia)\nAlbanian/Arbereshe (in Sicily and Calabria)\nSardinian language (in Sardinia)\nCorsican language (in North Sardinia)\nTwo dialects of Greek language, Griko dialect (in Grecìa Salentina) and Calabrian Greek (in Calabria)', 'Ladin\nSlovene', NULL, 'Other Italo-Dalmatian languages');
INSERT INTO Idioma () VALUES ('Ivory Coast', 'French', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Jamaica', 'English', NULL, NULL, 'Jamaican Patois', NULL);
INSERT INTO Idioma () VALUES ('Japan', 'None (Japanese has de facto status)', NULL, NULL, 'Japanese', NULL);
INSERT INTO Idioma () VALUES ('Jordan', 'Arabic', NULL, 'Circassian\nChechen\nArmenian', NULL, NULL);
INSERT INTO Idioma () VALUES ('Kazakhstan', 'Kazakh\nRussian', NULL, NULL, 'Kazakh', NULL);
INSERT INTO Idioma () VALUES ('Kenya', 'English\nSwahili', NULL, NULL, 'Swahili', NULL);
INSERT INTO Idioma () VALUES ('Kiribati', 'English', NULL, NULL, 'Kiribati', NULL);
INSERT INTO Idioma () VALUES ('North Korea', 'Korean', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('South Korea', 'Korean\nKorean Sign Language', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Kosovo', 'Albanian\nSerbian', 'Turkish', NULL, 'Albanian (nationwide)\nSerbian (Northern Kosovo)', NULL);
INSERT INTO Idioma () VALUES ('Kuwait', 'Standard Arabic', NULL, NULL, 'Kuwaiti Sign Language\nKuwaiti Arabic\nKuwaiti Persian', NULL);
INSERT INTO Idioma () VALUES ('Kyrgyzstan', 'Kyrgyz\nRussian', NULL, NULL, 'Kyrgyz', NULL);
INSERT INTO Idioma () VALUES ('Laos', 'Lao', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Latvia', 'Latvian', NULL, NULL, NULL, 'Russian');
INSERT INTO Idioma () VALUES ('Lebanon', 'Arabic', 'Arabic', 'Armenian', 'Arabic\nEnglish\nFrench', 'Arabic\nEnglish\nFrench');
INSERT INTO Idioma () VALUES ('Lesotho', 'Sotho\nEnglish', NULL, NULL, 'Sotho', NULL);
INSERT INTO Idioma () VALUES ('Liberia', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Libya', 'Arabic', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Liechtenstein', 'German', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Lithuania', 'Lithuanian', NULL, NULL, NULL, 'Russian');
INSERT INTO Idioma () VALUES ('Luxembourg', 'French\nGerman\nLuxembourgish', NULL, NULL, 'Luxembourgish', NULL);
INSERT INTO Idioma () VALUES ('Madagascar', 'French\nMalagasy', NULL, NULL, 'Malagasy', NULL);
INSERT INTO Idioma () VALUES ('Malawi', 'English\nChichewa', NULL, NULL, 'Chichewa', NULL);
INSERT INTO Idioma () VALUES ('Malaysia', 'Malay', 'Regional/State dialects', NULL, 'Malay', 'Malay\nMandarin Chinese\nCantonese\nTamil');
INSERT INTO Idioma () VALUES ('Maldives', 'Dhivehi', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Mali', 'French', 'Tamazight (Azawad district)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Malta', 'Maltese\nEnglish', NULL, NULL, 'Maltese', NULL);
INSERT INTO Idioma () VALUES ('Sovereign Military Order of Malta', 'Italian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Marshall Islands', 'English', NULL, NULL, 'Marshallese', NULL);
INSERT INTO Idioma () VALUES ('Mauritania', 'Arabic', NULL, NULL, 'Arabic\nFula\nSoninke\nWolof', 'French');
INSERT INTO Idioma () VALUES ('Mauritius', 'English\nMauritian Creole (Also known as ''Morisien'')', NULL, 'English', NULL, NULL);
INSERT INTO Idioma () VALUES ('Mexico', 'None (Spanish has de facto status)', NULL, NULL, '68 National languages', NULL);
INSERT INTO Idioma () VALUES ('Federated States of Micronesia', 'English', 'Chuukese (in Chuuk State)\nKosraean (in Kosrae State)\nPohnpeian (in Pohnpei State)\nYapese (in Yap State)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Moldova', 'Romanian', 'Gagauz\nRussian\nUkrainian', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Monaco', 'French', NULL, NULL, NULL, 'Monégasque');
INSERT INTO Idioma () VALUES ('Mongolia', 'Mongolian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Montenegro', 'Montenegrin', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Morocco', 'Arabic\nTamazight', NULL, NULL, 'Arabic', 'Darija (Moroccan Arabic)');
INSERT INTO Idioma () VALUES ('Mozambique', 'Portuguese', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Myanmar (Burma)', 'Burmese', 'Chin\nKachin\nKaren\nKarenni\nMon\nRakhine\nShan', NULL, NULL, 'English');
INSERT INTO Idioma () VALUES ('Namibia', 'English', 'German\nOshiwambo', NULL, 'Afrikaans', NULL);
INSERT INTO Idioma () VALUES ('Nauru', 'English\nNauruan', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Nepal', 'Nepali', NULL, NULL, 'all languages spoken as the mother tongue in Nepal', NULL);
INSERT INTO Idioma () VALUES ('Netherlands', 'Dutch\nFrisian (in the province Friesland)', 'English (in Curaçao, Sint Maarten, Sint Eustatius, Saba)\nPapiamento (in Aruba, Curaçao, Bonaire)', 'Dutch Low Saxon\nDutch Sign Language\nLimburgish\nSinte Romani\nYiddish', NULL, NULL);
INSERT INTO Idioma () VALUES ('New Zealand', 'English has de facto status\nMāori language\nNew Zealand Sign Language', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Nicaragua', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Niger', 'French', NULL, NULL, 'Arabic\nHausa\nFulfulde\nGulmancema\nKanuri\nZarma\nTamazight', NULL);
INSERT INTO Idioma () VALUES ('Nigeria', 'English', NULL, NULL, 'Hausa\nYoruba\nIgbo\nTiv', NULL);
INSERT INTO Idioma () VALUES ('Niue', 'English\nNiuean', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Norfolk Island', 'English\nNorfuk', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('North Macedonia', 'Macedonian\nAlbanian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Northern Cyprus', 'Turkish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Norway', 'Norwegian\nSami languages', 'Northern Sami\nLule Sami\nSouthern Sámi\nKven', 'Kven\nScandoromani', 'Bokmål (written)\nNynorsk (written)', NULL);
INSERT INTO Idioma () VALUES ('Oman', 'Arabic', NULL, 'Shehri', NULL, NULL);
INSERT INTO Idioma () VALUES ('Pakistan', 'Urdu\nEnglish', NULL, NULL, 'Urdu', 'Punjabi\nBalochi\nSindhi\nPashto');
INSERT INTO Idioma () VALUES ('Palau', 'English\nPalauan', 'Sonsorolese (in Sonsorol)\nTobian (in Hatohobei)\nJapanese (in Angaur)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Palestine', 'None (Arabic has de facto status)', NULL, NULL, NULL, 'English\nHebrew');
INSERT INTO Idioma () VALUES ('Panama', 'Spanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Papua New Guinea', 'English\nHiri Motu\nPNG Sign Language\nTok Pisin', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Paraguay', 'Spanish\nGuaraní', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Peru', 'Peruvian Spanish\nQuechua\nAymara\nAsháninka', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Philippines', 'Filipino\nEnglish', 'Aklanon (in the Visayas)\nBikol (in Luzon)\nCebuano (in the Visayas and Mindanao)\nChavacano (in Mindanao)\nHiligaynon (in the Visayas)\nIbanag (in Luzon)\nIlocano (in Luzon, official in La Union)\nIvatan (in Luzon)\nKapampangan (in Luzon)\nKinaray-a (in the Visayas)\nMaguindanao (in Mindanao)\nMaranao (in Mindanao)\nPangasinan (in Luzon)\nSambal (in Luzon)\nTagalog (in Luzon)\nTausug (in Mindanao)\nWaray (in the Visayas)\nYakan (in Mindanao)', 'Arabic (optional language)\nSpanish (optional language)\n(+ over 100 more minority languages)', 'Filipino\nFilipino Sign Language (national sign language)', NULL);
INSERT INTO Idioma () VALUES ('Poland', 'Polish', 'Kashubian (Pomeranian Voivodeship)', 'German (Opole Voivodeship)\nLithuanian (Puńsk commune)\nBelarusian (Podlaskie Voivodseship)\nCzech\nHebrew\nYiddish\nLemko\nKaraim\nArmenian\nRomani\nRussian\nSlovak\nTatar\nUkrainian', NULL, NULL);
INSERT INTO Idioma () VALUES ('Portugal', 'Portuguese', 'Mirandese (Terra de Miranda)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Qatar', 'Arabic', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Romania', 'Romanian', NULL, 'Armenian\nGerman\nHungarian\nRomani\nRussian\nSerbian\nSlovak\nTatar\nTurkish\nUkrainian', NULL, 'Aromanian');
INSERT INTO Idioma () VALUES ('Russia', 'Russian', '(33 languages)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Rwanda', 'English\nFrench\nKinyarwanda\nSwahili', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Sahrawi Arab Democratic Republic', 'Tamazight\nArabic\nSpanish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Saint Kitts and Nevis', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Saint Lucia', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Saint Vincent and the Grenadines', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Samoa', 'English', NULL, NULL, 'Samoan', NULL);
INSERT INTO Idioma () VALUES ('San Marino', 'Italian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('São Tomé and Príncipe', 'Portuguese', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Saudi Arabia', 'Arabic', NULL, 'Faifi\nRazihi\nMehri', NULL, 'Indian Languages\nFilipino \nBengali');
INSERT INTO Idioma () VALUES ('Senegal', 'French', NULL, NULL, 'Jola-Fogny\nMandinka\nPulaar\nSerer\nSoninke\nWolof', NULL);
INSERT INTO Idioma () VALUES ('Serbia', 'Serbian', NULL, '(15 languages)', NULL, NULL);
INSERT INTO Idioma () VALUES ('Seychelles', 'English\nFrench\nSeychellois Creole', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Sierra Leone', 'English', NULL, NULL, 'Krio', NULL);
INSERT INTO Idioma () VALUES ('Singapore', 'English\nMalay\nMandarin Chinese\nTamil', NULL, NULL, 'Malay', NULL);
INSERT INTO Idioma () VALUES ('Slovakia', 'Slovak', NULL, 'Bulgarian\nCzech\nGerman\nHungarian\nPolish\nRomani\nRusyn\nSerbian\nUkrainian', NULL, NULL);
INSERT INTO Idioma () VALUES ('Slovenia', 'Slovene', NULL, 'Hungarian (Dobrovnik, Hodoš, Lendava)\nItalian (Izola, Koper, Piran)\nCroatian (Metlika, Brežice)', NULL, NULL);
INSERT INTO Idioma () VALUES ('Solomon Islands', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Somalia', 'Arabic', NULL, NULL, 'Somali', NULL);
INSERT INTO Idioma () VALUES ('Somaliland', 'Arabic\nEnglish\nSomali', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('South Africa', 'Afrikaans\nEnglish\nSouthern Ndebele\nSotho\nNorthern Sotho\nSwazi\nTsonga\nTswana\nVenda\nXhosa\nZulu', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('South Ossetia', 'Ossetian\nRussian', 'Georgian', 'Georgian', NULL, NULL);
INSERT INTO Idioma () VALUES ('South Sudan', 'English', NULL, NULL, 'Arabic\nBari\nDinka\nLuo\nMurle\nNuer\nZande\n(60 other languages)', NULL);
INSERT INTO Idioma () VALUES ('Spain', 'Spanish', 'Catalan (Balearic Islands, Catalonia, Valencian Community)\nGalician (Galicia)\nOccitan (Catalonia)\nBasque (Basque Country, Navarra)', 'Astur-Leonese (Asturias)\nAragonese (Aragon)\nFala (Province of Cáceres)\nFrench\nPortuguese', NULL, NULL);
INSERT INTO Idioma () VALUES ('Sri Lanka', 'Sinhala\nTamil', NULL, NULL, 'Sinhala\nTamil', NULL);
INSERT INTO Idioma () VALUES ('Sudan', 'Arabic\nEnglish', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Suriname', 'Dutch', NULL, NULL, 'Sranan Tongo', NULL);
INSERT INTO Idioma () VALUES ('Sweden', 'Swedish', NULL, 'Finnish (Gällivare, Haparanda, Kiruna, Pajala, Övertorneå\nMeänkieli (Gällivare, Haparanda, Kiruna, Pajala, Övertorneå)\nSami (Arjeplog, Gällivare, Jokkmokk, Kiruna)', NULL, 'English\nRomani\nYiddish');
INSERT INTO Idioma () VALUES ('Switzerland', 'French (Bern, Fribourg, Geneva, Jura, Neuchâtel, Valais, Vaud)\nGerman (Aargau, Appenzell Ausserrhoden, Appenzell Innerrhoden, Basel-Landschaft, Basel-Stadt, Bern, Fribourg, Glarus, Graubünden, Lucerne, Nidwalden, Obwalden, Saint Gallen, Schaffhausen, Schwyz, Solothurn, Thurgau, Uri, Valais, Zug, Zürich)\nItalian (Ticino, Graubünden)\nRomansh (Graubünden)', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Syria', 'Arabic', 'Kurdish', 'Assyrian\nWestern Neo-Aramaic\nArmenian', NULL, NULL);
INSERT INTO Idioma () VALUES ('Taiwan', 'None (Mandarin Chinese has de facto status)', NULL, NULL, 'Taiwanese Mandarin\nTaiwanese Hokkien\nTaiwanese Hakka\nFormosan languages\nTaiwan Sign Language\nMatsu dialect\nWuqiu dialect', NULL);
INSERT INTO Idioma () VALUES ('Tajikistan', 'Tajik', NULL, NULL, 'Tajik', 'Russian');
INSERT INTO Idioma () VALUES ('Tanzania', 'Swahili\nEnglish', NULL, NULL, 'Swahili', NULL);
INSERT INTO Idioma () VALUES ('Thailand', 'Thai', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Togo', 'French', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Tokelau', 'English\nTokelauan', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Tonga', 'English\nTongan', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Transnistria', 'Moldovan\nRussian\nUkrainian', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Trinidad and Tobago', 'English', NULL, NULL, NULL, 'Trinidadian Creole');
INSERT INTO Idioma () VALUES ('Tunisia', 'Arabic', NULL, NULL, 'Arabic', 'Tunisian');
INSERT INTO Idioma () VALUES ('Turkey', 'Turkish', NULL, 'Kurdish', 'Turkish', NULL);
INSERT INTO Idioma () VALUES ('Turkmenistan', 'Turkmen', NULL, NULL, 'Turkmen', 'Russian');
INSERT INTO Idioma () VALUES ('Tuvalu', 'Tuvaluan\nEnglish', NULL, NULL, 'Tuvaluan\nEnglish', NULL);
INSERT INTO Idioma () VALUES ('Uganda', 'English\nSwahili', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Ukraine', 'Ukrainian', 'Russian (Autonomous Republic of Crimea)\nCrimean Tatar (Autonomous Republic of Crimea)', NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('United Arab Emirates', 'Arabic', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('United Kingdom and Crown dependencies etc.', 'None (English has de facto status)\nIrish and Ulster-Scots (in Northern Ireland)\nScots and Scottish Gaelic (in Scotland)\nWelsh (in Wales)\nPitcairnese (in Pitcairn Islands)\nGuernésiais and French (in Guernsey)\nJèrriais and French (in Jersey)\nManx (in Isle of Man)', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('United States', 'None (English has de facto status)', '(28 languages)', NULL, 'Several indigenous languages of recognized federal tribes', 'Spanish');
INSERT INTO Idioma () VALUES ('Uruguay', 'None (Spanish has de facto status)', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Uzbekistan', 'Uzbek', NULL, 'Uzbek\nKarakalpak and Uzbek in Karakalpakstan', NULL, 'Russian');
INSERT INTO Idioma () VALUES ('Vanuatu', 'English\nFrench', NULL, NULL, 'Bislama', NULL);
INSERT INTO Idioma () VALUES ('Vatican City', 'Italian\nLatin (formerly)', NULL, NULL, NULL, 'Swiss German');
INSERT INTO Idioma () VALUES ('Venezuela', 'Spanish\nVenezuelan Sign Language', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Vietnam', 'Vietnamese', NULL, 'Cantonese\nCham\nHmong\nKhmer\nLao\nMuong\nRade\nTay\nThai\nVietnamese sign languages', 'Vietnamese', NULL);
INSERT INTO Idioma () VALUES ('Yemen', 'Arabic', NULL, 'Mehri\nSoqotri', NULL, NULL);
INSERT INTO Idioma () VALUES ('Zambia', 'English', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Zanzibar', 'Swahili', NULL, NULL, NULL, NULL);
INSERT INTO Idioma () VALUES ('Zimbabwe', 'Chewa\nChibarwe\nEnglish\nKalanga\nKhoisan\nNambya\nNdau\nNdebele\nShangani\nShona\nSign language\nSotho\nTonga\nTswana\nVenda\nXhosa', NULL, NULL, NULL, NULL);
