INSERT INTO language () VALUES ('Abkhazia', 'Abkhaz\nRussian');
INSERT INTO language () VALUES ('Afghanistan', 'Persian (Dari)\nPashto');
INSERT INTO language () VALUES ('Albania', 'Albanian');
INSERT INTO language () VALUES ('Algeria', 'Arabic\nTamazight');
INSERT INTO language () VALUES ('Andorra', 'Catalan');
INSERT INTO language () VALUES ('Angola', 'Portuguese');
INSERT INTO language () VALUES ('Antigua and Barbuda', 'English');
INSERT INTO language () VALUES ('Argentina', 'None (Spanish has de facto status)');
INSERT INTO language () VALUES ('Armenia', 'Armenian');
INSERT INTO language () VALUES ('Artsakh', 'Armenian\nRussian');
INSERT INTO language () VALUES ('Australia', 'None (English has de facto status)');
INSERT INTO language () VALUES ('Austria', 'German');
INSERT INTO language () VALUES ('Azerbaijan', 'Azerbaijani');
INSERT INTO language () VALUES ('Bahamas', 'English');
INSERT INTO language () VALUES ('Bahrain', 'Arabic');
INSERT INTO language () VALUES ('Bangladesh', 'Bengali');
INSERT INTO language () VALUES ('Barbados', 'English');
INSERT INTO language () VALUES ('Belarus', 'Belarusian\nRussian');
INSERT INTO language () VALUES ('Belgium', 'Dutch\nFrench\nGerman');
INSERT INTO language () VALUES ('Belize', 'English');
INSERT INTO language () VALUES ('Benin', 'French');
INSERT INTO language () VALUES ('Bhutan', 'Dzongkha');
INSERT INTO language () VALUES ('Bolivia', 'Castilian (Spanish)\nAymara\nAraona\nBaure\nBésiro (Chiquitano)\nCanichana\nCavineño\nCayubaba\nChácobo\nChimán\nEse Ejja\nGuaraní\nGuarasu''we\nGuarayu\nItonama\nLeco\nMachajuyai-Kallawaya\nMachineri\nMaropa\nMojeño-Ignaciano\nMojeño-Trinitario\nMoré\nMosetén\nMovima\nPacawara\nPuquina\nQuechua\nSirionó\nTacana\nTapieté\nToromona\nUru-Chipaya\nWeenhayek\nYaminawa\nYuki\nYuracaré\nZamuco');
INSERT INTO language () VALUES ('Bosnia and Herzegovina', 'None (Bosnian, Croatian and Serbian all have de facto status)');
INSERT INTO language () VALUES ('Botswana', 'English');
INSERT INTO language () VALUES ('Brazil', 'Portuguese');
INSERT INTO language () VALUES ('Brunei', 'Malay\nEnglish');
INSERT INTO language () VALUES ('Bulgaria', 'Bulgarian');
INSERT INTO language () VALUES ('Burkina Faso', 'French');
INSERT INTO language () VALUES ('Burundi', 'French\nKirundi\nEnglish');
INSERT INTO language () VALUES ('Cambodia', 'Khmer');
INSERT INTO language () VALUES ('Cameroon', 'English\nFrench');
INSERT INTO language () VALUES ('Canada', 'English (Federal)\nFrench (Federal)');
INSERT INTO language () VALUES ('Cape Verde', 'Portuguese');
INSERT INTO language () VALUES ('Central African Republic', 'French\nSango');
INSERT INTO language () VALUES ('Chad', 'Arabic\nFrench');
INSERT INTO language () VALUES ('Chile', 'Chilean Spanish');
INSERT INTO language () VALUES ('China', 'Mandarin Chinese');
INSERT INTO language () VALUES ('Christmas Island', 'English, Mandarin Chinese, Malay');
INSERT INTO language () VALUES ('Cocos (Keeling) Islands', 'English, Cocos Malay');
INSERT INTO language () VALUES ('Colombia', 'Spanish');
INSERT INTO language () VALUES ('Comoros', 'Arabic\nComorian\nFrench');
INSERT INTO language () VALUES ('Democratic Republic of the Congo', 'French');
INSERT INTO language () VALUES ('Republic of the Congo', 'French');
INSERT INTO language () VALUES ('Cook Islands', 'English, Cook Islands Māori');
INSERT INTO language () VALUES ('Costa Rica', 'Spanish');
INSERT INTO language () VALUES ('Croatia', 'Croatian');
INSERT INTO language () VALUES ('Cuba', 'Spanish');
INSERT INTO language () VALUES ('Cyprus', 'Greek\nTurkish');
INSERT INTO language () VALUES ('Czech Republic', 'Czech\nSlovak');
INSERT INTO language () VALUES ('Denmark', 'Danish');
INSERT INTO language () VALUES ('Djibouti', 'Arabic\nFrench');
INSERT INTO language () VALUES ('Dominica', 'English');
INSERT INTO language () VALUES ('Dominican Republic', 'Spanish');
INSERT INTO language () VALUES ('East Timor', 'Portuguese\nTetum');
INSERT INTO language () VALUES ('Ecuador', 'Spanish\nQuechua (official language of intercultural relation)');
INSERT INTO language () VALUES ('Egypt', 'Arabic');
INSERT INTO language () VALUES ('El Salvador', 'Spanish');
INSERT INTO language () VALUES ('Equatorial Guinea', 'French\nPortuguese\nSpanish');
INSERT INTO language () VALUES ('Eritrea', 'Tigrinya');
INSERT INTO language () VALUES ('Estonia', 'Estonian');
INSERT INTO language () VALUES ('Eswatini', 'English\nSwazi');
INSERT INTO language () VALUES ('Ethiopia', 'Afar\nAmharic\nOromo\nSomali\nTigrinya');
INSERT INTO language () VALUES ('Fiji', 'English\nFijian\nFiji Hindi');
INSERT INTO language () VALUES ('Finland', 'Finnish\nSwedish');
INSERT INTO language () VALUES ('France', 'French');
INSERT INTO language () VALUES ('Gabon', 'French');
INSERT INTO language () VALUES ('Gambia', 'English');
INSERT INTO language () VALUES ('Georgia', 'Georgian');
INSERT INTO language () VALUES ('Germany', 'German');
INSERT INTO language () VALUES ('Ghana', 'English');
INSERT INTO language () VALUES ('Greece', 'Greek');
INSERT INTO language () VALUES ('Grenada', 'English');
INSERT INTO language () VALUES ('Guatemala', 'Spanish');
INSERT INTO language () VALUES ('Guinea', 'French');
INSERT INTO language () VALUES ('Guinea-Bissau', 'Portuguese');
INSERT INTO language () VALUES ('Guyana', 'English');
INSERT INTO language () VALUES ('Haiti', 'French\nHaitian Creole');
INSERT INTO language () VALUES ('Honduras', 'Spanish');
INSERT INTO language () VALUES ('Hungary', 'Hungarian');
INSERT INTO language () VALUES ('Iceland', 'Icelandic\nIcelandic Sign Language[citation needed]');
INSERT INTO language () VALUES ('India', 'Hindi\nEnglish');
INSERT INTO language () VALUES ('Indonesia', 'Indonesian');
INSERT INTO language () VALUES ('Iran', 'Persian');
INSERT INTO language () VALUES ('Iraq', 'Arabic\nKurdish');
INSERT INTO language () VALUES ('Ireland', 'Irish\nEnglish');
INSERT INTO language () VALUES ('Israel', 'Hebrew');
INSERT INTO language () VALUES ('Italy', 'Italian');
INSERT INTO language () VALUES ('Ivory Coast', 'French');
INSERT INTO language () VALUES ('Jamaica', 'English');
INSERT INTO language () VALUES ('Japan', 'None (Japanese has de facto status)');
INSERT INTO language () VALUES ('Jordan', 'Arabic');
INSERT INTO language () VALUES ('Kazakhstan', 'Kazakh\nRussian');
INSERT INTO language () VALUES ('Kenya', 'English\nSwahili');
INSERT INTO language () VALUES ('Kiribati', 'English');
INSERT INTO language () VALUES ('North Korea', 'Korean');
INSERT INTO language () VALUES ('South Korea', 'Korean\nKorean Sign Language');
INSERT INTO language () VALUES ('Kosovo', 'Albanian\nSerbian');
INSERT INTO language () VALUES ('Kuwait', 'Standard Arabic');
INSERT INTO language () VALUES ('Kyrgyzstan', 'Kyrgyz\nRussian');
INSERT INTO language () VALUES ('Laos', 'Lao');
INSERT INTO language () VALUES ('Latvia', 'Latvian');
INSERT INTO language () VALUES ('Lebanon', 'Arabic');
INSERT INTO language () VALUES ('Lesotho', 'Sotho\nEnglish');
INSERT INTO language () VALUES ('Liberia', 'English');
INSERT INTO language () VALUES ('Libya', 'Arabic');
INSERT INTO language () VALUES ('Liechtenstein', 'German');
INSERT INTO language () VALUES ('Lithuania', 'Lithuanian');
INSERT INTO language () VALUES ('Luxembourg', 'French\nGerman\nLuxembourgish');
INSERT INTO language () VALUES ('Madagascar', 'French\nMalagasy');
INSERT INTO language () VALUES ('Malawi', 'English\nChichewa');
INSERT INTO language () VALUES ('Malaysia', 'Malay');
INSERT INTO language () VALUES ('Maldives', 'Dhivehi');
INSERT INTO language () VALUES ('Mali', 'French');
INSERT INTO language () VALUES ('Malta', 'Maltese\nEnglish');
INSERT INTO language () VALUES ('Sovereign Military Order of Malta', 'Italian');
INSERT INTO language () VALUES ('Marshall Islands', 'English');
INSERT INTO language () VALUES ('Mauritania', 'Arabic');
INSERT INTO language () VALUES ('Mauritius', 'English\nMauritian Creole (Also known as ''Morisien'')');
INSERT INTO language () VALUES ('Mexico', 'None (Spanish has de facto status)');
INSERT INTO language () VALUES ('Federated States of Micronesia', 'English');
INSERT INTO language () VALUES ('Moldova', 'Romanian');
INSERT INTO language () VALUES ('Monaco', 'French');
INSERT INTO language () VALUES ('Mongolia', 'Mongolian');
INSERT INTO language () VALUES ('Montenegro', 'Montenegrin');
INSERT INTO language () VALUES ('Morocco', 'Arabic\nTamazight');
INSERT INTO language () VALUES ('Mozambique', 'Portuguese');
INSERT INTO language () VALUES ('Myanmar (Burma)', 'Burmese');
INSERT INTO language () VALUES ('Namibia', 'English');
INSERT INTO language () VALUES ('Nauru', 'English\nNauruan');
INSERT INTO language () VALUES ('Nepal', 'Nepali');
INSERT INTO language () VALUES ('Netherlands', 'Dutch\nFrisian (in the province Friesland)');
INSERT INTO language () VALUES ('New Zealand', 'English has de facto status\nMāori language\nNew Zealand Sign Language');
INSERT INTO language () VALUES ('Nicaragua', 'Spanish');
INSERT INTO language () VALUES ('Niger', 'French');
INSERT INTO language () VALUES ('Nigeria', 'English');
INSERT INTO language () VALUES ('Niue', 'English\nNiuean');
INSERT INTO language () VALUES ('Norfolk Island', 'English\nNorfuk');
INSERT INTO language () VALUES ('North Macedonia', 'Macedonian\nAlbanian');
INSERT INTO language () VALUES ('Northern Cyprus', 'Turkish');
INSERT INTO language () VALUES ('Norway', 'Norwegian\nSami languages');
INSERT INTO language () VALUES ('Oman', 'Arabic');
INSERT INTO language () VALUES ('Pakistan', 'Urdu\nEnglish');
INSERT INTO language () VALUES ('Palau', 'English\nPalauan');
INSERT INTO language () VALUES ('Palestine', 'None (Arabic has de facto status)');
INSERT INTO language () VALUES ('Panama', 'Spanish');
INSERT INTO language () VALUES ('Papua New Guinea', 'English\nHiri Motu\nPNG Sign Language\nTok Pisin');
INSERT INTO language () VALUES ('Paraguay', 'Spanish\nGuaraní');
INSERT INTO language () VALUES ('Peru', 'Peruvian Spanish\nQuechua\nAymara\nAsháninka');
INSERT INTO language () VALUES ('Philippines', 'Filipino\nEnglish');
INSERT INTO language () VALUES ('Poland', 'Polish');
INSERT INTO language () VALUES ('Portugal', 'Portuguese');
INSERT INTO language () VALUES ('Qatar', 'Arabic');
INSERT INTO language () VALUES ('Romania', 'Romanian');
INSERT INTO language () VALUES ('Russia', 'Russian');
INSERT INTO language () VALUES ('Rwanda', 'English\nFrench\nKinyarwanda\nSwahili');
INSERT INTO language () VALUES ('Sahrawi Arab Democratic Republic', 'Tamazight\nArabic\nSpanish');
INSERT INTO language () VALUES ('Saint Kitts and Nevis', 'English');
INSERT INTO language () VALUES ('Saint Lucia', 'English');
INSERT INTO language () VALUES ('Saint Vincent and the Grenadines', 'English');
INSERT INTO language () VALUES ('Samoa', 'English');
INSERT INTO language () VALUES ('San Marino', 'Italian');
INSERT INTO language () VALUES ('São Tomé and Príncipe', 'Portuguese');
INSERT INTO language () VALUES ('Saudi Arabia', 'Arabic');
INSERT INTO language () VALUES ('Senegal', 'French');
INSERT INTO language () VALUES ('Serbia', 'Serbian');
INSERT INTO language () VALUES ('Seychelles', 'English\nFrench\nSeychellois Creole');
INSERT INTO language () VALUES ('Sierra Leone', 'English');
INSERT INTO language () VALUES ('Singapore', 'English\nMalay\nMandarin Chinese\nTamil');
INSERT INTO language () VALUES ('Slovakia', 'Slovak');
INSERT INTO language () VALUES ('Slovenia', 'Slovene');
INSERT INTO language () VALUES ('Solomon Islands', 'English');
INSERT INTO language () VALUES ('Somalia', 'Arabic');
INSERT INTO language () VALUES ('Somaliland', 'Arabic\nEnglish\nSomali');
INSERT INTO language () VALUES ('South Africa', 'Afrikaans\nEnglish\nSouthern Ndebele\nSotho\nNorthern Sotho\nSwazi\nTsonga\nTswana\nVenda\nXhosa\nZulu');
INSERT INTO language () VALUES ('South Ossetia', 'Ossetian\nRussian');
INSERT INTO language () VALUES ('South Sudan', 'English');
INSERT INTO language () VALUES ('Spain', 'Spanish');
INSERT INTO language () VALUES ('Sri Lanka', 'Sinhala\nTamil');
INSERT INTO language () VALUES ('Sudan', 'Arabic\nEnglish');
INSERT INTO language () VALUES ('Suriname', 'Dutch');
INSERT INTO language () VALUES ('Sweden', 'Swedish');
INSERT INTO language () VALUES ('Switzerland', 'French (Bern, Fribourg, Geneva, Jura, Neuchâtel, Valais, Vaud)\nGerman (Aargau, Appenzell Ausserrhoden, Appenzell Innerrhoden, Basel-Landschaft, Basel-Stadt, Bern, Fribourg, Glarus, Graubünden, Lucerne, Nidwalden, Obwalden, Saint Gallen, Schaffhausen, Schwyz, Solothurn, Thurgau, Uri, Valais, Zug, Zürich)\nItalian (Ticino, Graubünden)\nRomansh (Graubünden)');
INSERT INTO language () VALUES ('Syria', 'Arabic');
INSERT INTO language () VALUES ('Taiwan', 'None (Mandarin Chinese has de facto status)');
INSERT INTO language () VALUES ('Tajikistan', 'Tajik');
INSERT INTO language () VALUES ('Tanzania', 'Swahili\nEnglish');
INSERT INTO language () VALUES ('Thailand', 'Thai');
INSERT INTO language () VALUES ('Togo', 'French');
INSERT INTO language () VALUES ('Tokelau', 'English\nTokelauan');
INSERT INTO language () VALUES ('Tonga', 'English\nTongan');
INSERT INTO language () VALUES ('Transnistria', 'Moldovan\nRussian\nUkrainian');
INSERT INTO language () VALUES ('Trinidad and Tobago', 'English');
INSERT INTO language () VALUES ('Tunisia', 'Arabic');
INSERT INTO language () VALUES ('Turkey', 'Turkish');
INSERT INTO language () VALUES ('Turkmenistan', 'Turkmen');
INSERT INTO language () VALUES ('Tuvalu', 'Tuvaluan\nEnglish');
INSERT INTO language () VALUES ('Uganda', 'English\nSwahili');
INSERT INTO language () VALUES ('Ukraine', 'Ukrainian');
INSERT INTO language () VALUES ('United Arab Emirates', 'Arabic');
INSERT INTO language () VALUES ('United Kingdom and Crown dependencies etc.', 'None (English has de facto status)\nIrish and Ulster-Scots (in Northern Ireland)\nScots and Scottish Gaelic (in Scotland)\nWelsh (in Wales)\nPitcairnese (in Pitcairn Islands)\nGuernésiais and French (in Guernsey)\nJèrriais and French (in Jersey)\nManx (in Isle of Man)');
INSERT INTO language () VALUES ('United States', 'None (English has de facto status)');
INSERT INTO language () VALUES ('Uruguay', 'None (Spanish has de facto status)');
INSERT INTO language () VALUES ('Uzbekistan', 'Uzbek');
INSERT INTO language () VALUES ('Vanuatu', 'English\nFrench');
INSERT INTO language () VALUES ('Vatican City', 'Italian\nLatin (formerly)');
INSERT INTO language () VALUES ('Venezuela', 'Spanish\nVenezuelan Sign Language');
INSERT INTO language () VALUES ('Vietnam', 'Vietnamese');
INSERT INTO language () VALUES ('Yemen', 'Arabic');
INSERT INTO language () VALUES ('Zambia', 'English');
INSERT INTO language () VALUES ('Zanzibar', 'Swahili');
INSERT INTO language () VALUES ('Zimbabwe', 'Chewa\nChibarwe\nEnglish\nKalanga\nKhoisan\nNambya\nNdau\nNdebele\nShangani\nShona\nSign language\nSotho\nTonga\nTswana\nVenda\nXhosa');
