INSERT INTO Moeda  VALUES ('Abkhazia', 'Abkhazian apsar', NULL, NULL, NULL, (none));
INSERT INTO Moeda  VALUES ('Abkhazia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO Moeda  VALUES ('Afghanistan', 'Afghan afghani', 'Af or Afs (pl.)', 'AFN', 'Pul', 100);
INSERT INTO Moeda  VALUES ('Akrotiri and Dhekelia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Albania', 'Albanian lek', 'Lek', 'ALL', 'Qintar', 100);
INSERT INTO Moeda  VALUES ('Alderney', 'Alderney pound', '£', NULL, 'Penny', 100);
INSERT INTO Moeda  VALUES ('Alderney', 'Sterling banknotes are issued by the Bank of England and by some banks in Scotland and Northern Ireland (incl. Danske Bank). Laws on legal tender vary between various jurisdictions.', '£', 'GBP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Alderney', 'Guernsey pound', '£', NULL, 'Penny', 100);
INSERT INTO Moeda  VALUES ('Algeria', 'Algerian dinar', 'DA', 'DZD', 'Santeem', 100);
INSERT INTO Moeda  VALUES ('Andorra', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Angola', 'Angolan kwanza', 'Kz', 'AOA', 'Cêntimo', 100);
INSERT INTO Moeda  VALUES ('Anguilla', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Antigua and Barbuda', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Argentina', 'Argentine peso', '$', 'ARS', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Armenia', 'Armenian dram', '֏', 'AMD', 'Luma', 100);
INSERT INTO Moeda  VALUES ('Artsakh', 'Artsakh dram', 'դր.', NULL, 'Luma', 100);
INSERT INTO Moeda  VALUES ('Artsakh', 'Armenian dram', '֏', 'AMD', 'Luma', 100);
INSERT INTO Moeda  VALUES ('Aruba', 'Aruban florin', 'ƒ', 'AWG', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Ascension Island', 'Saint Helena pound', '£', 'SHP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Australia', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Austria', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Azerbaijan', 'Azerbaijani manat', '₼', 'AZN', 'Qəpik', 100);
INSERT INTO Moeda  VALUES ('Bahamas, The', 'Bahamian dollar', '$', 'BSD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Bahrain', 'Bahraini dinar', 'BD', 'BHD', 'Fils', 1000);
INSERT INTO Moeda  VALUES ('Bangladesh', 'Bangladeshi taka', '৳', 'BDT', 'Poisha', 100);
INSERT INTO Moeda  VALUES ('Barbados', 'Barbadian dollar', '$', 'BBD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Belarus', 'Belarusian rubel', 'Rbl or Rbls (pl.)', 'BYN', 'Copeck', 100);
INSERT INTO Moeda  VALUES ('Belgium', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Belize', 'Belize dollar', '$', 'BZD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Benin', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Bermuda', 'Bermudian dollar', '$', 'BMD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Bhutan', 'Bhutanese ngultrum', 'Nu', 'BTN', 'Chetrum', 100);
INSERT INTO Moeda  VALUES ('Bhutan', 'Indian rupee', '₹', 'INR', 'Paisa', 100);
INSERT INTO Moeda  VALUES ('Bolivia', 'Bolivian boliviano', 'Bs', 'BOB', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Bonaire', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'KM', 'BAM', 'Fening', 100);
INSERT INTO Moeda  VALUES ('Botswana', 'Botswana pula', 'P', 'BWP', 'Thebe', 100);
INSERT INTO Moeda  VALUES ('Brazil', 'Brazilian real', 'R$', 'BRL', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('British Indian Ocean Territory', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('British Virgin Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Brunei', 'Brunei dollar', '$', 'BND', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Brunei', 'Singapore dollar', '$', 'SGD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Bulgaria', 'Bulgarian lev', 'Lev', 'BGN', 'Stotinka', 100);
INSERT INTO Moeda  VALUES ('Burkina Faso', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Burundi', 'Burundian franc', 'Fr', 'BIF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Cambodia', 'Cambodian riel', 'CR', 'KHR', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Cameroon', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Canada', 'Canadian dollar', '$', 'CAD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Cape Verde', 'Cape Verdean escudo', '$', 'CVE', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Cayman Islands', 'Cayman Islands dollar', '$', 'KYD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Central African Republic', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Central African Republic', 'Bitcoin (as legal tender)', '₿', NULL, 'Satoshi', 100000000);
INSERT INTO Moeda  VALUES ('Chad', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Chile', 'Chilean peso', '$', 'CLP', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('China, People''s Republic of', 'Renminbi', '¥', 'CNY', 'Jiao', 10);
INSERT INTO Moeda  VALUES ('Colombia', 'Colombian peso', '$', 'COP', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Comoros', 'Comorian franc', 'Fr', 'KMF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Congo, Democratic Republic of the', 'Congolese franc', 'Fr', 'CDF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Congo, Republic of the', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Cook Islands', 'Cook Islands dollar', '$', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('Cook Islands', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Costa Rica', 'Costa Rican colón', '₡', 'CRC', 'Céntimo', 100);
INSERT INTO Moeda  VALUES ('Côte d''Ivoire', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Croatia', 'Croatian kuna', 'kn', 'HRK', 'Lipa', 100);
INSERT INTO Moeda  VALUES ('Cuba', 'Cuban peso', '$', 'CUP', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Curaçao', 'Netherlands Antillean guilder', 'ƒ', 'ANG', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Cyprus', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Czech Republic', 'Czech koruna', 'Kč', 'CZK', 'Heller', 100);
INSERT INTO Moeda  VALUES ('Denmark', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO Moeda  VALUES ('Djibouti', 'Djiboutian franc', 'Fr', 'DJF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Dominica', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Dominican Republic', 'Dominican peso', '$', 'DOP', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('East Timor', 'United States dollar', '$', 'USD', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Ecuador', 'United States dollar', '$', 'USD', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Egypt', 'Egyptian pound', 'LE', 'EGP', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('El Salvador', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('El Salvador', 'Bitcoin (as legal tender)', '₿', NULL, 'Satoshi', 100000000);
INSERT INTO Moeda  VALUES ('Equatorial Guinea', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Eritrea', 'Eritrean nakfa', 'Nkf', 'ERN', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Estonia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Eswatini', 'Swazi lilangeni', 'L or E (pl.)', 'SZL', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Eswatini', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Ethiopia', 'Ethiopian birr', 'Br', 'ETB', 'Santim', 100);
INSERT INTO Moeda  VALUES ('Falkland Islands', 'Falkland Islands pound', '£', 'FKP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Faroe Islands', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO Moeda  VALUES ('Faroe Islands', 'Faroese króna', 'kr', NULL, 'Oyra', 100);
INSERT INTO Moeda  VALUES ('Fiji', 'Fijian dollar', '$', 'FJD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Finland', 'Euro', '€', 'EUR', 'Sentti', 100);
INSERT INTO Moeda  VALUES ('France', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('French Polynesia', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Gabon', 'Central African CFA franc', 'Fr', 'XAF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Gambia, The', 'Gambian dalasi', 'D', 'GMD', 'Butut', 100);
INSERT INTO Moeda  VALUES ('Georgia', 'Georgian lari', '₾', 'GEL', 'Tetri', 100);
INSERT INTO Moeda  VALUES ('Germany', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Ghana', 'Ghanaian cedi', '₵', 'GHS', 'Pesewa', 100);
INSERT INTO Moeda  VALUES ('Gibraltar', 'Gibraltar pound', '£', 'GIP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Greece', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Greenland', 'Danish krone', 'kr', 'DKK', 'Øre', 100);
INSERT INTO Moeda  VALUES ('Grenada', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Guatemala', 'Guatemalan quetzal', 'Q', 'GTQ', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Guernsey', 'Guernsey pound', '£', NULL, 'Penny', 100);
INSERT INTO Moeda  VALUES ('Guernsey', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Guinea', 'Guinean franc', 'Fr', 'GNF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Guinea-Bissau', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Guyana', 'Guyanese dollar', '$', 'GYD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Haiti', 'Haitian gourde', 'G', 'HTG', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Honduras', 'Honduran lempira', 'L', 'HNL', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Hong Kong', 'Hong Kong dollar', '$', 'HKD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Hungary', 'Hungarian forint', 'Ft', 'HUF', 'Fillér', 100);
INSERT INTO Moeda  VALUES ('Iceland', 'Icelandic króna', 'kr', 'ISK', 'Eyrir', 100);
INSERT INTO Moeda  VALUES ('India', 'Indian rupee', '₹', 'INR', 'Paisa', 100);
INSERT INTO Moeda  VALUES ('Indonesia', 'Indonesian rupiah', 'Rp', 'IDR', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Iran', 'Iranian rial', 'Rl or Rls (pl.)', 'IRR', 'Rial', 1);
INSERT INTO Moeda  VALUES ('Iraq', 'Iraqi dinar', 'ID', 'IQD', 'Fils', 1000);
INSERT INTO Moeda  VALUES ('Ireland', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Isle of Man', 'Manx pound', '£', NULL, 'Penny', 100);
INSERT INTO Moeda  VALUES ('Isle of Man', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Israel', 'Israeli new shekel', '₪', 'ILS', 'Agora', 100);
INSERT INTO Moeda  VALUES ('Italy', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Jamaica', 'Jamaican dollar', '$', 'JMD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Japan', 'Japanese yen', '¥', 'JPY', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Jersey', 'Jersey pound', '£', NULL, 'Penny', 100);
INSERT INTO Moeda  VALUES ('Jersey', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Jordan', 'Jordanian dinar', 'JD', 'JOD', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('Kazakhstan', 'Kazakhstani tenge', '₸', 'KZT', 'Tıyn', 100);
INSERT INTO Moeda  VALUES ('Kenya', 'Kenyan shilling', 'Sh or Shs (pl.)', 'KES', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Kiribati', 'Kiribati dollar', '$', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('Kiribati', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Korea, North', 'North Korean won', '₩', 'KPW', 'Chon', 100);
INSERT INTO Moeda  VALUES ('Korea, South', 'South Korean won', '₩', 'KRW', 'Jeon', 100);
INSERT INTO Moeda  VALUES ('Kosovo', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Kuwait', 'Kuwaiti dinar', 'KD', 'KWD', 'Fils', 1000);
INSERT INTO Moeda  VALUES ('Kyrgyzstan', 'Kyrgyz som', 'som', 'KGS', 'Tyiyn', 100);
INSERT INTO Moeda  VALUES ('Laos', 'Lao kip', '₭', 'LAK', 'Att', 100);
INSERT INTO Moeda  VALUES ('Latvia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Lebanon', 'Lebanese pound', 'LL', 'LBP', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('Lesotho', 'Lesotho loti', 'L or M (pl.)', 'LSL', 'Sente', 100);
INSERT INTO Moeda  VALUES ('Lesotho', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Liberia', 'Liberian dollar', '$', 'LRD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Libya', 'Libyan dinar', 'LD', 'LYD', 'Dirham', 1000);
INSERT INTO Moeda  VALUES ('Liechtenstein', 'Swiss franc', 'Fr', 'CHF', 'Rappen', 100);
INSERT INTO Moeda  VALUES ('Lithuania', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Luxembourg', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Macau', 'Macanese pataca', 'MOP$', 'MOP', 'Avo', 100);
INSERT INTO Moeda  VALUES ('Macau', 'Hong Kong dollar', '$', 'HKD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Madagascar', 'Malagasy ariary', 'Ar', 'MGA', 'Iraimbilanja', 5);
INSERT INTO Moeda  VALUES ('Malawi', 'Malawian kwacha', 'K', 'MWK', 'Tambala', 100);
INSERT INTO Moeda  VALUES ('Malaysia', 'Malaysian ringgit', 'RM', 'MYR', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Maldives', 'Maldivian rufiyaa', 'Rf', 'MVR', 'Laari', 100);
INSERT INTO Moeda  VALUES ('Mali', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Malta', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Marshall Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Mauritania', 'Mauritanian ouguiya', 'UM', 'MRU', 'Khoums', 5);
INSERT INTO Moeda  VALUES ('Mauritius', 'Mauritian rupee', 'Re or Rs (pl.)', 'MUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Mexico', 'Mexican peso', '$', 'MXN', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Micronesia', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Moldova', 'Moldovan leu', 'Leu or Lei (pl.)', 'MDL', 'Ban', 100);
INSERT INTO Moeda  VALUES ('Monaco', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Mongolia', 'Mongolian tögrög', '₮', 'MNT', 'Möngö', 100);
INSERT INTO Moeda  VALUES ('Montenegro', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Montserrat', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Morocco', 'Moroccan dirham', 'DH', 'MAD', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Mozambique', 'Mozambican metical', 'Mt', 'MZN', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Myanmar', 'Burmese kyat', 'K or Ks (pl.)', 'MMK', 'Pya', 100);
INSERT INTO Moeda  VALUES ('Namibia', 'Namibian dollar', '$', 'NAD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Namibia', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Nauru', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Nepal', 'Nepalese rupee', 'Re or Rs (pl.)', 'NPR', 'Paisa', 100);
INSERT INTO Moeda  VALUES ('Netherlands', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('New Caledonia', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('New Zealand', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Nicaragua', 'Nicaraguan córdoba', 'C$', 'NIO', 'Centavo', 100);
INSERT INTO Moeda  VALUES ('Niger', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Nigeria', 'Nigerian naira', '₦', 'NGN', 'Kobo', 100);
INSERT INTO Moeda  VALUES ('Niue', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Niue', 'Niue dollar', '$', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('North Macedonia', 'Macedonian denar', 'DEN', 'MKD', 'Deni', 100);
INSERT INTO Moeda  VALUES ('Northern Cyprus', 'Turkish lira', '₺', 'TRY', 'Kuruş', 100);
INSERT INTO Moeda  VALUES ('Norway', 'Norwegian krone', 'kr', 'NOK', 'Øre', 100);
INSERT INTO Moeda  VALUES ('Oman', 'Omani rial', 'RO', 'OMR', 'Baisa', 1000);
INSERT INTO Moeda  VALUES ('Pakistan', 'Pakistani rupee', 'Re or Rs (pl.)', 'PKR', 'Paisa', 100);
INSERT INTO Moeda  VALUES ('Palau', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Palestine', 'Israeli new shekel', '₪', 'ILS', 'Agora', 100);
INSERT INTO Moeda  VALUES ('Palestine', 'Jordanian dinar', 'JD', 'JOD', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('Panama', 'Panamanian balboa', 'B/', 'PAB', 'Centésimo', 100);
INSERT INTO Moeda  VALUES ('Panama', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Papua New Guinea', 'Papua New Guinean kina', 'K', 'PGK', 'Toea', 100);
INSERT INTO Moeda  VALUES ('Paraguay', 'Paraguayan guaraní', '₲', 'PYG', 'Céntimo', 100);
INSERT INTO Moeda  VALUES ('Peru', 'Peruvian sol', 'S/', 'PEN', 'Céntimo', 100);
INSERT INTO Moeda  VALUES ('Philippines', 'Philippine peso', '₱', 'PHP', 'Sentimo', 100);
INSERT INTO Moeda  VALUES ('Pitcairn Islands', 'New Zealand dollar', '$', 'NZD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Pitcairn Islands', 'Pitcairn Islands dollar', '$', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('Poland', 'Polish złoty', 'zł', 'PLN', 'Grosz', 100);
INSERT INTO Moeda  VALUES ('Portugal', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Qatar', 'Qatari riyal', 'QR', 'QAR', 'Dirham', 100);
INSERT INTO Moeda  VALUES ('Romania', 'Romanian leu', 'Leu or Lei (pl.)', 'RON', 'Ban', 100);
INSERT INTO Moeda  VALUES ('Russia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO Moeda  VALUES ('Rwanda', 'Rwandan franc', 'Fr', 'RWF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Saba', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Sahrawi Republic', 'Algerian dinar', 'DA', 'DZD', 'Santeem', 100);
INSERT INTO Moeda  VALUES ('Sahrawi Republic', 'Mauritanian ouguiya', 'UM', 'MRU', 'Khoums', 5);
INSERT INTO Moeda  VALUES ('Sahrawi Republic', 'Moroccan dirham', 'DH', 'MAD', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Sahrawi Republic', 'Sahrawi peseta', 'Pta or Pts (pl.)', NULL, 'Centime', 100);
INSERT INTO Moeda  VALUES ('Saint Helena', 'Saint Helena pound', '£', 'SHP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('Saint Kitts and Nevis', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Saint Lucia', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Saint Vincent and the Grenadines', 'Eastern Caribbean dollar', '$', 'XCD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Samoa', 'Samoan tālā', '$', 'WST', 'Sene', 100);
INSERT INTO Moeda  VALUES ('San Marino', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('São Tomé and Príncipe', 'São Tomé and Príncipe dobra', 'Db', 'STN', 'Cêntimo', 100);
INSERT INTO Moeda  VALUES ('Saudi Arabia', 'Saudi riyal', 'Rl or Rls (pl.)', 'SAR', 'Halala', 100);
INSERT INTO Moeda  VALUES ('Senegal', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Serbia', 'Serbian dinar', 'DIN', 'RSD', 'Para', 100);
INSERT INTO Moeda  VALUES ('Seychelles', 'Seychellois rupee', 'Re or Rs (pl.)', 'SCR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Sierra Leone', 'Sierra Leonean leone', 'Le', 'SLE', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Singapore', 'Singapore dollar', '$', 'SGD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Singapore', 'Brunei dollar', '$', 'BND', 'Sen', 100);
INSERT INTO Moeda  VALUES ('Sint Eustatius', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Sint Maarten', 'Netherlands Antillean guilder', 'ƒ', 'ANG', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Slovakia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Slovenia', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Solomon Islands', 'Solomon Islands dollar', '$', 'SBD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Somalia', 'Somali shilling', 'Sh or Shs (pl.)', 'SOS', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Somaliland', 'Somaliland shilling', 'Sh or Shs (pl.)', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('South Africa', 'South African rand', 'R', 'ZAR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('South Ossetia', 'Russian rouble', '₽', 'RUB', 'Kopeck', 100);
INSERT INTO Moeda  VALUES ('Spain', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('South Sudan', 'South Sudanese pound', NULL, 'SSP', 'Piaster', 100);
INSERT INTO Moeda  VALUES ('Sri Lanka', 'Sri Lankan rupee', 'Re or Rs (pl.)', 'LKR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Sudan', 'Sudanese pound', 'LS', 'SDG', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('Suriname', 'Surinamese dollar', '$', 'SRD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Sweden', 'Swedish krona', 'kr', 'SEK', 'Öre', 100);
INSERT INTO Moeda  VALUES ('Switzerland', 'Swiss franc', 'Fr', 'CHF', 'Rappen', 100);
INSERT INTO Moeda  VALUES ('Syria', 'Syrian pound', 'LS', 'SYP', 'Piastre', 100);
INSERT INTO Moeda  VALUES ('Taiwan, Republic of China', 'New Taiwan dollar', '$', 'TWD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Tajikistan', 'Tajikistani somoni', 'SM', 'TJS', 'Diram', 100);
INSERT INTO Moeda  VALUES ('Tanzania', 'Tanzanian shilling', 'Sh or Shs (pl.)', 'TZS', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Thailand', 'Thai baht', '฿', 'THB', 'Satang', 100);
INSERT INTO Moeda  VALUES ('Togo', 'West African CFA franc', 'Fr', 'XOF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Tonga', 'Tongan paʻanga', 'T$', 'TOP', 'Seniti', 100);
INSERT INTO Moeda  VALUES ('Transnistria', 'Transnistrian ruble', 'р', NULL, 'Kopeck', 100);
INSERT INTO Moeda  VALUES ('Trinidad and Tobago', 'Trinidad and Tobago dollar', '$', 'TTD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Tunisia', 'Tunisian dinar', 'DT', 'TND', 'Millime', 1000);
INSERT INTO Moeda  VALUES ('Turkey', 'Turkish lira', '₺', 'TRY', 'Kuruş', 100);
INSERT INTO Moeda  VALUES ('Turkmenistan', 'Turkmenistani manat', 'm', 'TMT', 'Tenge', 100);
INSERT INTO Moeda  VALUES ('Turks and Caicos Islands', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Tuvalu', 'Tuvaluan dollar', '$', NULL, 'Cent', 100);
INSERT INTO Moeda  VALUES ('Tuvalu', 'Australian dollar', '$', 'AUD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Uganda', 'Ugandan shilling', 'Sh or Shs (pl.)', 'UGX', NULL, (none));
INSERT INTO Moeda  VALUES ('Ukraine', 'Ukrainian hryvnia', '₴', 'UAH', 'Kopeck', 100);
INSERT INTO Moeda  VALUES ('United Arab Emirates', 'United Arab Emirates dirham', 'Dh or Dhs (pl.)', 'AED', 'Fils', 100);
INSERT INTO Moeda  VALUES ('United Kingdom', 'Sterling', '£', 'GBP', 'Penny', 100);
INSERT INTO Moeda  VALUES ('United States', 'United States dollar', '$', 'USD', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Uruguay', 'Uruguayan peso', '$', 'UYU', 'Centésimo', 100);
INSERT INTO Moeda  VALUES ('Uzbekistan', 'Uzbekistani soum', 'soum', 'UZS', 'Tiyin', 100);
INSERT INTO Moeda  VALUES ('Vanuatu', 'Vanuatu vatu', 'VT', 'VUV', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Vatican City', 'Euro', '€', 'EUR', 'Cent', 100);
INSERT INTO Moeda  VALUES ('Venezuela', 'Venezuelan sovereign bolívar', 'Bs.S', 'VES', 'Céntimo', 100);
INSERT INTO Moeda  VALUES ('Venezuela', 'Venezuelan digital bolívar', 'Bs.D', 'VED', 'Céntimo', 100);
INSERT INTO Moeda  VALUES ('Vietnam', 'Vietnamese đồng', '₫', 'VND', 'Hào', 10);
INSERT INTO Moeda  VALUES ('Wallis and Futuna', 'CFP franc', 'Fr', 'XPF', 'Centime', 100);
INSERT INTO Moeda  VALUES ('Yemen', 'Yemeni rial', 'Rl or Rls (pl.)', 'YER', 'Fils', 100);
INSERT INTO Moeda  VALUES ('Zambia', 'Zambian kwacha', 'K', 'ZMW', 'Ngwee', 100);
INSERT INTO Moeda  VALUES ('Zimbabwe', 'RTGS dollar', '$', NULL, 'Cent', 100);
